### ISSUE TITLE
Raids are still very very challenging 

### ISSUE THREAD

**Issue by Bishooi** [SoloCraftServer/bugtracker#10]
## 🐛 Bug report

The pre bis gear was good made some content doable :)!!!! The issue stays tho tanks dont seem to get much aoe threat even if you pause and unpause, Healers are going oom in the matter of 10 seconds in a fight plus they dont really heal that much. Dps do seem to be doing decently well!
### Expected behavior

Trying to get it to feel more doable with healers not being instantly oom and tanks to get aoe threat and be able to hold it and not watch the dps and heals get one shot because the tank lost threat and never gets it back
### Steps to reproduce
1.
2.
3.
Ty for the current fix. It means alot to see you actually working on your server :)

**Comment by SoloCraftServer** [comment]
I think there is a misunderstanding here, the bots are designed for PvP, levelling and dungeons, I only enabled them in raids last week as support and they are not ment to solo all raids ingame which is inpossible to do since blizzlike raids do require tactics.
