### ISSUE TITLE
Anubisath Defenders in AQ40

### ISSUE THREAD

**Issue by hivpositive** [SoloCraftServer/bugtracker#101]
Pulling one of these trash mobs results in 3 or 4 getting pulled. (I Was able to pull the first one in the room on it's own.)
Also the aggro range is kind of high, more than 30 yards.

You should be able to pull and kill all of these one by one.
https://youtu.be/uW10hUYsFqA?t=1371

### Steps to reproduce
1.Get to trash after Princess Huhuran in AQ40.
2. Try pulling one defender at a time.

**Comment by SoloCraftServer** [comment]
Will be fixed after next restart.
