### ISSUE TITLE
Gothik Phase 2

### ISSUE THREAD

**Issue by Rekojet** [SoloCraftServer/bugtracker#105]
## 🐛 Bug report
Naxxramas Gothik the Harvester, raid ID 4413, date 26/05/23 between 4:00 pm and 4:15 pm servertime, charactername Ragetotem.

During phase 2 when the boss ports in the middle of the room and the door opens, a lot of death knight mobs from phase 1 spawned as the ghosts came in. 

Never happened to me before. I wasn't able to reprodruce it because the boss died.

**Comment by SoloCraftServer** [comment]
Yes It was scripted like months ago (player suggestions) that to make it possible with playerbots. P2 opens the door and you'll be able to AoE the ghosts and focus on boss right.
