### ISSUE TITLE
Alterac Valley Alliance

### ISSUE THREAD

**Issue by Evisceratechuck** [SoloCraftServer/bugtracker#106]
## 🐛 Bug report
#1 Problem:
Alliance bots doesn't attack hordes last boss, instead the spawn at the last horde GY and run all the way back to re-cap whatever useless middle GY that's been re-capped by horde.

#2 Problem:
Horde always "magically" (No graveyard or cave) spawn out of nowhere outside their end-boss entrance, making it impossible for players to try and kill the boss on their own.

#1 Solution: 
Alliance bots should focus the nearest objective, if they spawn at hordes base GY, they should obviously go for the boss as their next objective.

#2 Solution: 
Bots shouldn't be able to spawn out of nowhere without a spirit healer.

Reproduce 1 & 2 problem:
Play alliance, enter AV, back-cap last GYs, wait for alliance/horde to spawn.

**Comment by SoloCraftServer** [comment]
Alliance bots DO attack the bosses, they follow their objectives. And there is no such thing as "magically" spawning. It is blizzlike and it is from their AV Trinket.
