### ISSUE TITLE
Bugged Riding skill - Jemmou level 41 Mage

### ISSUE THREAD

**Issue by Jemmou** [SoloCraftServer/bugtracker#107]
## 🐛 Bug report

I bought the riding skill from the Darkspear, level 41 at honored rep, yet I cannot ride my raptor.

![Jemmou Riding](https://github.com/SoloCraftServer/bugtracker/assets/134813298/6c7cd216-bc2b-4186-8a30-c0d79bdc78e3)

Thank you for any help!

**Comment by SoloCraftServer** [comment]
Clear your cache folder (WDB) and it should be fixed, your cache is messed up because of your previous private server (not blizzlike)

**Comment by Jemmou** [comment]
ok thank you for the help!
