### ISSUE TITLE
Seal of Ascension Quest cant be turned in

### ISSUE THREAD

**Issue by Metty92** [SoloCraftServer/bugtracker#112]
## 🐛 Bug report

Hello, 
I cant turn the last Quest for the Seal of Ascesion in. The Mob Vaelan has no question mark above his head. I just can talk to him.

The Quest i necessary to obtain the key for UBRS

Greetings

**Comment by SoloCraftServer** [comment]
Please close your WoW client and clear your cache files, (remove the WDB folder)
