### ISSUE TITLE
In Blackfathom Deeps dungeon, "Argent Guard Thaelrid" doesn't give the quest "Blackfathom Villainy"

### ISSUE THREAD

**Issue by Hyde7548** [SoloCraftServer/bugtracker#116]
## 🐛 Bug report
When going in the Blackfathom Deeps dungeon in Ashenvale, there is a NPC inside called "Agent Guard Thaelrid" (https://www.wowhead.com/classic/npc=4787/argent-guard-thaelrid) that is supposed to give the quest "Blackfathom Villainy" (https://www.wowhead.com/classic/quest=1200/blackfathom-villainy) to both Horde and Alliance. 

I have run this dungeon twice on an alliance character of a level > 18 and the quest was not available. 

Sorry, I didn't take a screenshot. However, I ran the command "/run print(C_QuestLog.IsQuestFlaggedCompleted(1200))" to check and the result was "false" as expected.

### Expected behavior

The expected behavior would be that the quest giver gives the quest.

### Steps to reproduce

1. Go to Blackfathom Deeps with an alliance character (in my case it was a Dwarf Priest of lvl ~23 if I remember correctly).

**Comment by SoloCraftServer** [comment]
Alliance needs this prequest first: https://classicdb.com/?quest=1198

**Comment by Hyde7548** [comment]
Multiple sources say that the first quest is not a hard prerequisite and that you can actually pick it up without completing the first part.
Icy Veins Guide: https://www.icy-veins.com/wow-classic/blackfathom-deeps-quests-guide
Wowhead comment section: https://www.wowhead.com/classic/quest=1200/blackfathom-villainy#comments
