### ISSUE TITLE
Raid not possible in World Boss area in Feralas (north-east for nightmare dragon)

### ISSUE THREAD

**Issue by Hyde7548** [SoloCraftServer/bugtracker#117]
## 🐛 Bug report

This bug only concernes the Feralas nightmare dragon area, as I was able to form raids in Lord Kazzak, Azuregos, and at least 2 of the other nightmare dragons locations (didn't even try in the Darkshire region as there are no mobs and the dragon was not there).

When trying to enter raid mode in this north-east Feralas area, I receive the error message displayed when trying to form a raid outside of the designated world bosses area.

Again, sorry no screenshot, I can go back and take one if needed.

### Expected behavior

This specific area should be treated as a world boss area, and thus we should be able to form raids.

### Steps to reproduce
1. Go in this area and try to make a raid.

**Comment by SoloCraftServer** [comment]
Works perfectly fine to me, make sure you are not too far from the boss ( & area)

![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/effc3d20-775b-4c9f-a239-64c4badeb5c5)
