### ISSUE TITLE
Bank extra bags not working properly

### ISSUE THREAD

**Issue by mt0870** [SoloCraftServer/bugtracker#120]
## 🐛 Bug report
I have a VIP account (Mazian87). Called up bank with .bank command. Purchased 1st bag slot, added 6 slot bag. Now cannot remove bag even when bank is totally empty. Purchased 2nd bag slot, added 10 slot bag, no additional slots appeared in bank. 

### Expected behavior

Purchased bag slots should allow bags to be inserted or replaced when empty, and should also provide additional slots.

### Steps to reproduce
1. VIP account
2. .bank
3. Purchase bag slot, add bag (i added 6 slot bag). Now cannot remove bag even when empty. Added 2nd bag, no additional slots.
![Bank bags](https://github.com/SoloCraftServer/bugtracker/assets/137766823/4615db31-b605-41a4-beb7-fe24da0b5ad2)

**Comment by SoloCraftServer** [comment]
It works perfectly fine to me, also never got a report about it since our release. Try clear your cache files and try again.
