### ISSUE TITLE
Spirit tap buff - Priest

### ISSUE THREAD

**Issue by InsanityFlea** [SoloCraftServer/bugtracker#121]
## 🐛 Bug report
After killing a mob with experience gain, spirit tap buff is not being applied.
### Expected behavior
buff applies after killing a mob which grants experience
https://wowpedia.fandom.com/wiki/Spirit_Tap

### Steps to reproduce
1. put 5 talent points in spirit tap
2. kill a mob for experience

**Comment by InsanityFlea** [comment]
Proc was just very low, even on 5 talent points

**Comment by InsanityFlea** [comment]
100% chance doesn't apply after every kill, only 15% of the time.

**Comment by SoloCraftServer** [comment]
Works as intended. Try solo kill and you will see it has a 100% chance.

https://us.forums.blizzard.com/en/wow/t/spirit-tap-doesnt-proc-in-groups-all-that-much/286252

**Comment by InsanityFlea** [comment]
Thank you
