### ISSUE TITLE
Character sound - Rogue

### ISSUE THREAD

**Issue by Joyhce** [SoloCraftServer/bugtracker#123]
## 🐛 Bug report

Most of the time when I play my rogue, the character sound doesn't work (skills, weapons damage for exemple), especially when I'm fighting mobs, I've tried on différent characters, and it the same issue.

### Expected behavior

When you're fighting mobs or in BG or everything else, I'd like to ear every character sound like weapons, skills and the rest like the real classic wow back in the day if it's possible.

### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
This is not a bug, please reset your UI (User interface)
