### ISSUE TITLE
Boat from grom gol to UC broken

### ISSUE THREAD

**Issue by Ralada** [SoloCraftServer/bugtracker#125]
## 🐛 Bug report
Once i get into the boat from grom gol to undercity i get disconnected.

### Expected behavior
Travel to undercity.

### Steps to reproduce
1. [image](https://github.com/SoloCraftServer/bugtracker/assets/140760075/36d17c2c-2027-482e-9fe8-d53f7f2f9618)
2.get into the boat
3.that's all.

**Comment by SoloCraftServer** [comment]
Works perfectly fine. Try disable your addons or make sure you use a clean client (download ours).
