### ISSUE TITLE
Cannot send or receive in-game mail

### ISSUE THREAD

**Issue by CELENION** [SoloCraftServer/bugtracker#127]
## 🐛 Bug report
My character has received in-game mail. Some of the mail was received days ago. As I recently leveled to 60, there is a fairly large quantity of mail from bots returning my items to me - probably 5+ pages of mail.

The mailbox icon on the minimap is showing. When I open a mailbox, the inbox tab is completely blank and I cannot see or interact with any mail. Similarly, if I try to send mail to any character the UI appears to work, but when I click send it grays out the send button and does not send the mail. I am attaching screenshots illustrating the empty mailbox, the send UI before clicking send, and the send UI after clicking send.

I have already tried relogging, relogging with all addons disabled, and a complete UI reset by deleting my interface, WTF, and WDB folders.

![image](https://github.com/SoloCraftServer/bugtracker/assets/120788556/64680125-cc60-4e3d-b768-e893cd3c8924)
![image](https://github.com/SoloCraftServer/bugtracker/assets/120788556/82cdc426-96a4-4a9b-a40c-089a047e4e02)
![image](https://github.com/SoloCraftServer/bugtracker/assets/120788556/90c11707-36e4-4d9b-9348-9683c1e95d55)

### Expected behavior
Inbound mail should be visible in mailbox and outbound mail should be sendable.

### Steps to reproduce
Apologies, unsure how to reproduce this bug as it does not appear to be affecting my other accounts/characters.

**Comment by SoloCraftServer** [comment]
Do not abuse it otherwise you will get locked like this.
