### ISSUE TITLE
Items disappear from bags after trading to bot in instance and being returned via mail.

### ISSUE THREAD

**Issue by yakboy287** [SoloCraftServer/bugtracker#130]
## 🐛 Bug report
When running Wailing Caverns on my warrior (Spartacus, lvl 31 during the run), I traded a number of items to a few bots to clear out bag space.  I did this over the course of a few runs, each with different groups.  Some of the groups were disbanded due to logging out, others due to leaving the party.  Afterward, the items traded were sent to me via the in-game mail.  Shortly after recovering these items from the mailbox, I logged out to check another character and then logged back in to my warrior. When I checked my bags, there were several gaps that had not been there before and I was missing several items I had specifically looked out before logging out.

### Expected behavior
From what I understand, the bots should mail you items traded to them after the group is disbanded, and the items should stay in your inventory.

### Steps to reproduce
1. While in an instance, trade items to several bots (I used maybe 8-10 bots over the course of the runs, and it was a large number of items.  I do not know if it was more than the mailbox limit or not).
2. Disband the group
3. Wait for mail to be sent containing the traded items (~1 hour?)
4. log out (I was in an inn so it was instant if that matters)
5. log into another character (in this case it was on a second account, so from my main account's POV I just logged out and back in)
6. log out and lot back onto the first character and check bags.

**Comment by SoloCraftServer** [comment]
Do not trade tons of items to clear out your bags, you probably hit the mail cap so it bugged out.
