### ISSUE TITLE
[Quest] The Nightmare Manifest

### ISSUE THREAD

**Issue by Rekojet** [SoloCraftServer/bugtracker#131]
## 🐛 Bug report

https://www.wowhead.com/classic/quest=8736/the-nightmare-manifests

It is currently not possible to accomplish this quest on the server. It is not bugged, but there are some issues related to the quest and server mechanics .

- This quest requires a raid group to be completed. Or, it is not possible to spawn a raid group composed of bots in Moonglade. 

- Even with the help of several other players, each one will only be able to spawn 4 bots.

- Those players would all have to be from the same faction. As they are not able to be in a raid group, Horde and Alliance player will appear hostile to each other. Or, the quest tales place in Nighthaven, which is a neutral town. This means that any damage done to a player of the opposite faction will trigger the spawn of guards and lead to a wipe.

- The quest requires to maintain Keeper Remulos alive until Tyrande appears. The healer bots are not able to do that.

### Expected behavior

Here is a guide explaining precisely the quest mechanics. Just select "The Nightmare Manifests (RAID)" on the Guide Navigation on the left of the screen.

https://www.wowhead.com/classic/guide/scepter-of-the-shifting-sands-scarab-lord-legendary-mount#the-nightmare-manifests-raid

### Steps to reproduce
1. Take the quest from Keeper Remulos and launch the event.

A solution to this issue could be to skip this quest in the same way as the Molten Core attunement quest, by automatically consider it as achieved once the raid event is launched.

**Comment by SoloCraftServer** [comment]
Will be applied after next restart (raid groups with bots)
