### ISSUE TITLE
Alzzin's Minion in dire maul should have loot table - id is 11460

### ISSUE THREAD

**Issue by azerith30** [SoloCraftServer/bugtracker#133]
## 🐛 Bug report
Alzzin's Minion in dire maul should have loot table - id is 11460 for him. they are the imps that come out after boss kill in Dire maul east

### Expected behavior
https://classicdb.ch/?npc=11460 - You can check loot table there. I tried to get blue sapphires off them since they dont exist on your server apparently lol. you might want to look into that as well

### Steps to reproduce
1.Kill last boss
2.Kill imps
3.immediatley imps dissappear and no loot on bodies before they disappear either.

**Comment by SoloCraftServer** [comment]
The loot table is no issue, they just despawn once the boss dies. I will take a look.
