### ISSUE TITLE
[Quest] The Wrath of Neptulon

### ISSUE THREAD

**Issue by Rekojet** [SoloCraftServer/bugtracker#134]
## 🐛 Bug report

There is an issue with the following quest : https://www.wowhead.com/classic/quest=8729/the-wrath-of-neptulon

This quest requires to kill a summoned WB in Azshara : https://www.wowhead.com/classic/npc=15571/maws 

Players are not able to spawn a raid group at that location. 

Even with the help of other players, they would all have to be from the same faction as bots have the tendency to attack hostile targets while engaged in combat (use of aoe abilities when a hostile target is near them, this includes opposite faction players and bots).

### Expected behavior

This quest in not bugged but due to server and bot mechanics it is not achievable without a raid group.

### Steps to reproduce
1. Go at the location in Azshara and use Arcanite Buoy to start the quest.

**Comment by SoloCraftServer** [comment]
Will be fixed after next server restart
