### ISSUE TITLE
Ravenholdt Reputation

### ISSUE THREAD

**Issue by Rekojet** [SoloCraftServer/bugtracker#136]
## 🐛 Bug report
 
Grinding Syndicate mobs in Hillsbrad Foothills doesn't give any reputation toward the Ravenholdt faction. 

### Expected behavior

Each kill of a Syndricate mob should increase Ravenholdt reputation by 5 points with blizzlike rates.

https://www.wowhead.com/classic/faction=349/ravenholdt

### Steps to reproduce
1. Go to Durnholde keep.
2. Kill some mobs. 
3.

**Comment by SoloCraftServer** [comment]
![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/a37a67db-d990-4a1f-9cf2-d8ea98d48fe1)
