### ISSUE TITLE
Seal of Ascension Quest Bugged

### ISSUE THREAD

**Issue by wowmantrav** [SoloCraftServer/bugtracker#139]
![2023-10-12 13_08_31-World of Warcraft](https://github.com/SoloCraftServer/bugtracker/assets/147760148/1a9b44a2-2b6d-4b53-bb18-3b0dbc9ab121)
## 🐛 Bug report
After getting the forged seal of ascension, Vaelan no longer has the turn-in for me. I have closed WoW and cleared cache/WTF/WDB folder but it still isn't working. I also tried disabling all of my addons.

### Expected behavior
According to the other issues in this forum, other players have completed by following the above instruction but mine won't work.

### Steps to reproduce
1. Clear cache/delete folders
2. Log in and talk to Vaelan
3. Go through his dialogue and talk again. No quest turn-in.

**Comment by SoloCraftServer** [comment]
Close your game and remove the WDB folder.
