### ISSUE TITLE
Warrior Talents Visual bug

### ISSUE THREAD

**Issue by Wellfiredk** [SoloCraftServer/bugtracker#142]
I have encountered a bug where I was following a guide from icy veins and the talents wasnt showing up as in the guide. I have posted some screenshots to help explain the situation.
In game I have 3 talents to choose from, but only 1 can be chosen (Anticipation on the right). I was also able to choose 
Shield Specialization on the second row, although I havent spent the 5 points to unlock it. This talent should be on the first
row of talents though. To help explain, ive posted a screenshot from icy veins to show how the talents should look.
The first row should be Shield Specialization and Anticipation, instead its Improved Bloodrage, Toughness and Anticipation, but
only the last one can be picked.

<img width="467" alt="Warrior Talents" src="https://github.com/SoloCraftServer/bugtracker/assets/148540448/a4367e84-996d-458e-9bd8-7a8d47dd92b5">
<img width="471" alt="Warrior Talents 2" src="https://github.com/SoloCraftServer/bugtracker/assets/148540448/e74614d2-d772-41be-851a-e2b9b13f49ce">
<img width="547" alt="Warrior Talents 3" src="https://github.com/SoloCraftServer/bugtracker/assets/148540448/d7a5a41c-e709-403a-a2a7-5caf38a5951f">

**Comment by Wellfiredk** [comment]
And just to add, I can still play the game and it seems so far I can choose the right talents from the guide on Icy Veins, its just not in the "right" order visually.

**Comment by SoloCraftServer** [comment]
Don't report invalid stuff. Your probably played on a weird custom server so your files seem to be messed up.
Download our client.

![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/6fc675ae-0a09-4882-876d-d54ac8e5f49e)
