### ISSUE TITLE
The Dreamer Has Awakened quest in Darkshore is currently impossible

### ISSUE THREAD

**Issue by GamingEmerald** [SoloCraftServer/bugtracker#146]
## 🐛 Bug report
The Dreamer Has Awakened quest in Darkshore is currently impossible, as the escort NPC spawns in the wrong area and just vanishes when you talk with him.

### Expected behavior
The escort NPC is meant to spawn in the Grove of the Ancients, and when you accept his quest, you're meant to escort him to Maestra's Post in Ashenvale, making sure he stays awake along the way. https://www.youtube.com/watch?v=V_sXobA90f0

### Steps to reproduce
Simply look at his intended spawn, notice he isn't there. Then run to Maestra's post, using /tar Ker until you find him in the building. Accept the quest, and he simply vanishes/despawns. You can run up the road all the way back to his intended location, using /tar Ker along the way, but you'll never find him. When he respawns, he respawns back at Maestra's Post and not the Grove Of The Ancients.

**Comment by SoloCraftServer** [comment]
The reported quest works perfectly fine.
https://www.wowhead.com/classic/quest=5321/the-sleeper-has-awakened#videos:id=171164
![p1](https://github.com/SoloCraftServer/bugtracker/assets/116836123/acaa7de9-ca83-49a6-9c83-1dc563d1226b)
![p2](https://github.com/SoloCraftServer/bugtracker/assets/116836123/a5860d48-23c0-4db0-8b3e-b5acb257fe9e)
![p3](https://github.com/SoloCraftServer/bugtracker/assets/116836123/d92234d7-5383-411b-9659-6bdcd3375a2d)
![p4](https://github.com/SoloCraftServer/bugtracker/assets/116836123/a0a443b8-dc99-485c-9879-db2074ec8975)
![p5](https://github.com/SoloCraftServer/bugtracker/assets/116836123/7a80cf4a-1689-44ad-a888-33c2ca83cbef)
