### ISSUE TITLE
Super-seller 680 fails to spawn

### ISSUE THREAD

**Issue by Luio** [SoloCraftServer/bugtracker#147]
## 🐛 Bug report
The npc Super-seller 680 (https://www.wowhead.com/classic/npc=12246/super-seller-680), who sells specific recipes unique to them, and appears at 40,80 in Desolace whenever the Gizleton's caravan reaches its southern destination is simply never spawning, even when the caravan is seen to reach the destination and despawn. I have followed the Gizleton's caravan on at least 3 trips, Vendor-Tron 1000 (https://www.wowhead.com/classic/npc=12245/vendor-tron-1000) does spawn as normal when the caravan reaches its northern destination (although the caravan npcs do not, this is another bug in itself but doesnt impede gameplay in any way), but Super-seller 680 does not spawn, ever, when the caravan reaches the southern destination. I have also waited for a full caravan trip at the southern destination to verify it does not spawn, and it never did.

### Expected behavior
The expected behaviour is that when the caravan reaches the southern destination and despawns, the npcs automatically respawn stationary at the location, alongside the npc Super-seller 680, who sells various items and recipes unique to them. This can be seen in wowhead as per previous links, but here are some more examples:
https://youtu.be/bqSipMJh46s
https://wowwiki-archive.fandom.com/wiki/Super-Seller_680#:~:text=The%20Super%2DSeller%20680&text=is%20a%20level%2D36%20trade,kodo%20caravan%20run%20by%20goblins.
https://wowpedia.fandom.com/wiki/Super-Seller_680

### Steps to reproduce
1. Stand at coordinates (40,80)
2.Wait for Gizleton Caravan to arrive to this location.
3.Watch as it despawns and the npc Super-seller 680 does not spawn.

**Comment by SoloCraftServer** [comment]
It works perfectly fine, becomes visible once NPC Rigger Gizelton is 100 yards from the vendor. Tested with my player account as well.

![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/6584755a-63df-4591-bfc2-30051c3f8d79)

**Comment by Luio** [comment]
I'll get a screenshot next time if I see it happen again, might have just fixed itself on a server reset. Really happy to see it working anyhow, I wasted a lot of time that day following that caravan. Gonna go get me them recipes!
