### ISSUE TITLE
Chromaggus 'heals'/evades

### ISSUE THREAD

**Issue by mishirimi** [SoloCraftServer/bugtracker#149]
## 🐛 Bug report
Chromaggus 'heals' quite a bit throughout the encounter, often when low health. I have not yet figured out the conditions, but happens every other encounter (trying to down him). Makes a hard fight impossible when this happens. I suspect it has something to do with him evading for a split second and thus health going up

### Expected behaviour
He should not be 'healing'.

### Steps to reproduce
1. I really have to figure this one out. Just heads-up, this bug is out there. Will try to add more info if I managed to gather any.

**Comment by SoloCraftServer** [comment]
"When the player dies, Chromaggus is healed for a significant amount of health"
