### ISSUE TITLE
Problem in PartyBot Control Panel Addon

### ISSUE THREAD

**Issue by AKSXXX** [SoloCraftServer/bugtracker#15]
## 🐛 Bug report
When switching class roles in Addon, the spawned bot can sometimes have the wrong role.
Closing and reopening the addon UI seems to help.

### Expected behavior
Always spawn bot with the selected role.

### Steps to reproduce
1. Do all steps wihthout closing addon UI
2. Select warrior tank
3. Spawn bot
4. Verify warrior is a tank (has shield)
5. Change role to dps
6. Spawn bot
7. New warrior is also a tank

**Comment by SoloCraftServer** [comment]
Will be fixed with the new version (v1.1) tomorrow
