### ISSUE TITLE
Range and Healers bot's not follow 

### ISSUE THREAD

**Issue by Plamen-Purvanov** [SoloCraftServer/bugtracker#150]
Hello,

From a day ago i notice i have to spawn button Come for Healers or Rdps or they do what they want and walk in other way and not follow me. I notice the mdps and tanks follow me without problem.

**Comment by SoloCraftServer** [comment]
Hello, it looks like you've enabled the partybot distance command.

You can turn it off by using the command ".partybot distance off"

**Comment by Plamen-Purvanov** [comment]
Hello,
Yes, distance off, works for me. Thx anyway. :)
