### ISSUE TITLE
Parachute cloak 

### ISSUE THREAD

**Issue by Seshiir2** [SoloCraftServer/bugtracker#151]
## 🐛 Bug report
I jumped off the cliff in Ashara to get to the bottom where the naga are at by the beach and when I jumped off I had the parachute cloak equipped and off cooldown and I hit the button and slow fall activated but when I reached the ground with it still active I received 3k damage from fall damage 

### Expected behavior
I should not have received fall damage from the glide 

### Steps to reproduce
1.obtain parachute cloak 
2.jump from high cliff 
3.reach ground “safley “ while it’s still active and it should still give you fall damage but it’s not supposed to

**Comment by SoloCraftServer** [comment]
Tested several times and couldn't reproduce it, please upload a video.
