### ISSUE TITLE
.mod xp command broken

### ISSUE THREAD

**Issue by Dunlanace** [SoloCraftServer/bugtracker#152]
## 🐛 Bug report
The .mod xp [1-5] command does not seem to affect the exp gain at all

### Expected behavior
getting 40% more exp at xp 5 than the base 3

### Steps to reproduce
1.get VIP
2.use .mod xp 5
3. not seeing an increase in xp gain

**Comment by SoloCraftServer** [comment]
Once you become VIP,  XP rates are x5 by default. This does not apply while in party since the XP is getting split over all party members.
