### ISSUE TITLE
Alterac valley Two new bugs

### ISSUE THREAD

**Issue by Evisceratechuck** [SoloCraftServer/bugtracker#154]
## 🐛 Bug report

Whenever bots kill in AV they sometimes get x5 or x10 amount of kills, ending up with hundreds of kills within minutes.

Whenever priests die in AV they sometimes go into spirit of redemption mode for up to 30minutes or more, while in this state they can be HIT by enemies and hence starts to pool up many many bots for long periods of time. This sometimes locks the game from progressing further.

**Comment by SoloCraftServer** [comment]
You really should follow the report guide next time and report 1 bug only each time, this is the second time already. Anyway I cannot reproduce this so I need more info, does it happen on level 60 BGs or below?
