### ISSUE TITLE
Outdoor RAID bosses - silithus

### ISSUE THREAD

**Issue by mishirimi** [SoloCraftServer/bugtracker#156]
## 🐛 Bug report
I cannot create outdoor raid to defeat Emissary Roman Khan (silithus outdoor raid boss). Tried 5-man, no luck. Same with abyssal lords :/

### Expected behavior
Should be able to create a raid there around.

### Steps to reproduce
1. Go to the bones.
2. Create RAID.

**Comment by SoloCraftServer** [comment]
I've disabled the power burn spell and it is perfectly soloable now (5 man group @ level 60)
