### ISSUE TITLE
Hunter - Pet trouble

### ISSUE THREAD

**Issue by Alphamatbrother** [SoloCraftServer/bugtracker#157]
## 🐛 Bug report
Hi

I play Hunter, Whenever i tame a pet, the pet sometime disapear forever, i try to call pet again but nothing happens.
I have to tame the pet again and again and it does the same thing.

Secondly in pet concern, i can't feed the pet, it feed myself instead, of course i've used the right spell to feed the pet.

For the rest the hunter class seems to be fine, thank you guys for the effort you put into the game cheers.

**Comment by SoloCraftServer** [comment]
Hello, make sure you clear your cache files, there are no issues regarding feeding pets.
