### ISSUE TITLE
change race bug

### ISSUE THREAD

**Issue by dantufis** [SoloCraftServer/bugtracker#158]
## 🐛 Bug report
after using the token to change race from gnome to human, as mage this issue happens: 
-all fireball spells are unlearned  (can be learned again)
-frost armor unlearned(can be learned again)
- portals and teleports from alliance become horde. (can be learned again)
- wand deleted (my poor doomfinger gone)
- reputation with other city other city become friendly, i was exalted with ironforge now i am friendly,  but swift ram works

![image](https://github.com/SoloCraftServer/bugtracker/assets/42617683/486aec97-1145-49fc-804e-8f31c40e8f57)
![image](https://github.com/SoloCraftServer/bugtracker/assets/42617683/e2c49a44-2bb3-4a4a-a1c1-00655668bfd5)

**Comment by SoloCraftServer** [comment]
Some spells do reset, such as portals. Missing items are automatically sent to your mailbox. Also, make sure to clear your cache folder while the client is not running. If you are missing anything, please open a ticket in-game.
