### ISSUE TITLE
Bot dispal magic / decurse

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#16]
## 🐛 Bug report
When the full raid gets curses or dispels, all bots that can decurses do it on the very same target and dispel characters one by one.

### Expected behavior
Decurses or dispel magic targets by bots should me more random. I think the same script is runing for  all the bots thats why they decide to decurse the same target all at once instead of picking a random dude in the raid.

Steps to reproduce
1. Pull an MC boss that do curses or magic
2. See party bots affected by those afflicitons
3. See all bots are dispeling the same target on after another

**Comment by SoloCraftServer** [comment]
Fixed on PTR, I'll close the case once it is pushed to live.
The healers will only dispel/remove curse IF the affected player is in the same group with the healer (and in a raid map). 
Does not apply to dungeons or battlegrounds

**Comment by Altair484** [comment]
Thank you so every group must have 1 class that can decurse or remove magic when full raid is affected by those afflictions if I understand well. If I am not wrong, it will be hard for horde raid to have dispels on magic, since only priest class can do that. It would mean they need 8 priest for 40 man raid ? (why not, time to bring some Spriests :D)
