### ISSUE TITLE
Quest: Pyrewood Ambush - reward locked

### ISSUE THREAD

**Issue by pawelkudlak** [SoloCraftServer/bugtracker#160]
## 🐛 Bug report

Quest: Pyrewood Ambush in Silverpin Forest, after defeating all attackers, there is information from Faerlaia that we won, but "?" is grey, I can choose an reward, but nothing happens
### Expected behavior

https://www.youtube.com/watch?v=naTQplIv3Lg
### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
Works fine for me (1.12.1 client). Try deleting your cache files and disable addons.
