### ISSUE TITLE
Bodley doesn't recover pieces of Lord Valthalak's amulet

### ISSUE THREAD

**Issue by generom** [SoloCraftServer/bugtracker#161]
## 🐛 Bug report
Bodley does not give dialog to recover pieces of Lord Valthalak's Amulet.

### Expected behavior

It should be possible to recover pieces of Lord Valthalak's Amulet by talking to Bodley.

[Top piece](https://wowgaming.altervista.org/aowow/?spell=27542)
[Left piece](https://wowgaming.altervista.org/aowow/?spell=27544)
[Amulet](https://wowgaming.altervista.org/aowow/?spell=27537)

similar issue [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9727)

### Steps to reproduce
1.Delete item from bags after completing quest to get it
2.Try to recover it by talking to Bodley NPC in front of BRS
3.Nothing happens.

**Comment by SoloCraftServer** [comment]
Fixed after next restart, I'll close this report once it is live.
