### ISSUE TITLE
Talent does not work "Improved Heroic Strike"

### ISSUE THREAD

**Issue by Deniszen** [SoloCraftServer/bugtracker#165]
## 🐛 Bug report
After taking the first and second rank talents, the ability still costs 15 rage

### Expected behavior
[wowhead](https://www.wowhead.com/classic/spell=12664/improved-heroic-strike) link 
![image](https://github.com/SoloCraftServer/bugtracker/assets/19793217/fa11148a-adb8-4946-acde-4f35069c0635)

### Steps to reproduce
1.  Troll warrior level 15

**Comment by SoloCraftServer** [comment]
Works perfectly fine to me. Try clear your cache files.
