### ISSUE TITLE
[QUEST] Pamela's Doll - 5149 - 

### ISSUE THREAD

**Issue by stadoo** [SoloCraftServer/bugtracker#166]
## 🐛 Bug report

all doll parts are not spawned.
Accepted the quest several times and canceled it again.

please check, thanks.

### Expected behavior

https://www.wowhead.com/classic/quest=5149/pamelas-doll

### Steps to reproduce
1. start the quest
2. go to the House
3.

**Comment by wbraunber** [comment]
To me the quest worked fine

**Comment by stadoo** [comment]
I test it with a other pc, there work it to. Sorry. I deleted the cache maybe thats help for the next time.
