### ISSUE TITLE
Cant skin mob after bot loot attempt

### ISSUE THREAD

**Issue by captainspork87** [SoloCraftServer/bugtracker#167]
## 🐛 Bug report
So my issue im experiencing is that whenever I try to skin mobs one of my bot members already attempts to loot for money and it doesnt let me skin mob saying creature must be looted first. Is there a command to stop bots from looting corpses since they only loot money?

**Comment by nobodyinteresting** [comment]
What version of the engine are you running? I've never had a bot try to loot anything. I didn't even know they could.

**Comment by captainspork87** [comment]
> What version of the engine are you running? I've never had a bot try to loot anything. I didn't even know they could.

The bot engine I cant tell so I assume the server is using the latest one. Are you asking the client version because I downloaded the one from the first download mirror on this site.

**Comment by SoloCraftServer** [comment]
Bots cannot loot mobs. Pleave provide any source e.g a video or tell me how to reproduce the issue. Also try set your loot to master loot.
