### ISSUE TITLE
Mother Smolderweb boss

### ISSUE THREAD

**Issue by Kazzba** [SoloCraftServer/bugtracker#168]
## 🐛 Bug report
When you kill the boss Mother Smolderweb in LBRS you and your team will constantly be netted. I tried to reset the dungeon and go again but I kept getting netted to the ground indefinitely. I was netted for 8 second, 2 second delay and a new net appears. I managed to circumvent this issue bu simply skipping her by using stealth.

### Expected behavior
Nothing should happen after you kill her.

### Steps to reproduce
1. Engange encounter with Mother Smolderweb
2. Kill her.
3. You should now be netted.

**Comment by nobodyinteresting** [comment]
I'm not sure how [Mother's Milk](https://www.wowhead.com/classic/spell=16468/mothers-milk#comments) worked in vanilla, but that's what is causing this.

**Comment by SoloCraftServer** [comment]
This is blizzlike, you need to cure it (like Abolish Poison)
