### ISSUE TITLE
Baron geddon wont fight after several wipes

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#17]
## 🐛 Bug report
Baron Geddon got bugged and continues patrolling after beein pulled

video : https://streamable.com/xo5vv9

### Expected behavior
He should attack and fight :)

### Steps to reproduce
1. Pull baron geddon
2. Wipe
3. Try it again and he got bug

**Comment by SoloCraftServer** [comment]
I've tried to reproduce it several times but it was working fine, please open a ticket next time if this happens again. You also can try relogging first.
