### ISSUE TITLE
Mother's milk cant be delivered even though you are poisoned.

### ISSUE THREAD

**Issue by wenalyzercom** [SoloCraftServer/bugtracker#172]
## 🐛 Bug report

![image](https://github.com/SoloCraftServer/bugtracker/assets/3832719/44c1677e-d734-4458-947e-979b9061487c)

### Expected behavior
You should be able to deliver the quest when you are poisoned with mothers milk poisoned from LBRS

### Steps to reproduce
1.Mother's milk cant be delivered even though you are poisoned.
2.
3.

**Comment by SoloCraftServer** [comment]
![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/4ec41f90-e59f-49b8-bc27-a7fe0593dfc0)
It works fine to me, I can't reproduce the report. Are you using the 1.12 or 1.14 client?
