### ISSUE TITLE
Orb of Orahil Quest Bug

### ISSUE THREAD

**Issue by Loosepaw** [SoloCraftServer/bugtracker#177]
## 🐛 Bug report
I completed most of a questline for the Orb of Orahil and the last piece didn't trigger. I may have missed a step, and broken the questline. A few people on Wowhead say "But first, you need to cleanse the orb, and you don't want to turn anything in before hand because you will fail the quest forever (unless they fixed that finally)." *1
1. I went to my class trainer at levels 40-41 and accepted a new quest to seek out Menara Voidrender.
2. I turned in and completed Knowledge of Orahil.
3. I accepted Fragments of the Orb of Orahil and went and got the Infernal Orb from the warlocks in Desolace.
4. I sought out Tabatha in the Duskwallow Marsh, turned in Fragments of the Orb of Orahil, and took Cleansing the Orb of Orahil.
5.  I killed the demon, cleansing the Infernal Orb, and completing her quest Cleansing the Orb of Orahil.
6. I picked up the quest, Returning the Cleansed Orb.
7. I took the Cleansed Infernal Orb back to Menara Voidrender and turned in Returning the Cleansed Orb.
8. Menara Voidrender started the void animation to put a chosen demon into the Cleansed Orb.
9. I wasn't sure what I did wrong at this point, but I was confused because I had not sought out a chosen demon.
10. The Completed Orb of Dar'Orahil was never offered to me by Menara Voidrender. 

Sources:
*1. https://www.wowhead.com/classic/quest=1799/fragments-of-the-orb-of-orahil

### Expected behavior
https://www.youtube.com/watch?v=TAOxrk_n9z4

### Steps to reproduce
I have not tried to reproduce the bug. However, a friend of mine with a warlock on this server did the same quest line last week and killed an infernal as part of the quest and I didn't. Therein lies the issue I believe. If I were to repeat this process I would...
1. Level a new warlock to 40
2. Do the questline
11. Not forget the felhound or infernal side quest.

**Comment by Loosepaw** [comment]
I will add that I am unable to take the Shards of a Fellhound or Infernal quest lines, they are shown by my questing add-on but the givers don't have them anymore.

**Comment by Loosepaw** [comment]
Character name is Vaermina

**Comment by SoloCraftServer** [comment]
Hello Vaermina, please open a ticket ingame about this report so I can give you the quest again.

**Comment by Loosepaw** [comment]
I am unable to claim this reward. Not sure what is wrong. Menara Voidrender is not triggering the completion step.
![image](https://github.com/SoloCraftServer/bugtracker/assets/159080370/84950fc9-b684-47b5-aff4-ea0cc63f699f)
