### ISSUE TITLE
Partybots may dash off to chase a previously focusMarked mob

### ISSUE THREAD

**Issue by necropola** [SoloCraftServer/bugtracker#178]
## 🐛 Bug report
Partybots may dash off to chase a previously focusMarked mob which respawned (far away) with the TargetMarker still/again on it. This mostly happens with the Warrior bot who gets into "combat" on a regular basis by using BloodRage.

### Expected behavior
Partybots should not dash off.

### Steps to reproduce
1. In open world: Target, mark and engage a mob with your bots i. e.
```
.partybot focusmark skull
/run SetRaidTarget("TARGET",8)
.partybot attackstart
```

2. Kill the mob, don't remove the TargetMark, don't use `.partybot clearmarks` and walk away.

3. Wait for the mob to respawn (far away) and wait for your Warrior bot to use BloodRage.

4. Observe the Warriror bot dashing off to chase the previously marked target. 

### Additional information
- The relevant code in vMangos appears to be: https://github.com/vmangos/core/blob/8e09be6745b8876751deb19e6c03522c0fec39f4/src/game/PlayerBots/PartyBotAI.cpp#L373-L384
- I'm not sure that mobs should still/again have the TargetMark on them on respawn, but I never played Retail Vanilla.

**Comment by SoloCraftServer** [comment]
Thats why we have .partybot clearmarks.  The mark itself doesn't get auto removed (blizzlike) so they will keep focusing to the target

**Comment by necropola** [comment]
I don't understand. You (are you [ratkosrb](https://github.com/ratkosrb)?) added `.partybots clearmarks` ([7803682](https://github.com/vmangos/core/commit/78036823ac35b6c809f7107886482d6bf48825bf)) so that creatures may respawn with TargetMarkers still on them just for the sake of **bilzzlike-ness**?

**Comment by necropola** [comment]
FYi, setting the loot mode removes (for whatever reason) all raid markers one may have set in the world, e. g. `/ffa` clears them all. So I've added this to my `bot-reset` macro.
