### ISSUE TITLE
AV Disconnect

### ISSUE THREAD

**Issue by Veldane** [SoloCraftServer/bugtracker#18]
## 🐛 Bug report

When getting disconnected by the server during Alterac Valley it will boot the person out of the instance and give deserter and any items gathered such as the armor scraps will be lost.
### Expected behavior

Keep a person long enough for the afk flag to hit
### Steps to reproduce
1. server disconnect issue
2. join an AV battle
3. get disconnected by server.

**Comment by SoloCraftServer** [comment]
We need to find out why you were getting kicked in the first pleace, there were no server DC issues in general, might be a false positive from the anti cheat system. Could you please tell me your lastest actions before you were kicked and on which character?

Thank you

**Comment by Veldane** [comment]
I was playing as Veldane and previously I was riding my mount on the road
and got disconnected
It might be my wireless internet but it doesn't give me a lot of trouble
usually.

**Comment by SoloCraftServer** [comment]
Contacted ingame.
