### ISSUE TITLE
partybot commands wrong target

### ISSUE THREAD

**Issue by youbi449** [SoloCraftServer/bugtracker#180]
## 🐛 Bug report
When i use the following command : .partybot attackstart

while targetting correct ennemy it focus one of my group member like you can see in the screen below
![image](https://github.com/SoloCraftServer/bugtracker/assets/93451423/aece208c-366a-4535-9e6b-37b2f735ced2)
same for .partybot pull

### Expected behavior
it should attackstart the correct target

### Steps to reproduce
1. just spam .partybot pull or .partybot attackstart

**Comment by SoloCraftServer** [comment]
You keep reporting invalid reports dude
