### ISSUE TITLE
Princess Moira Bronzebeard

### ISSUE THREAD

**Issue by covidfriendly** [SoloCraftServer/bugtracker#183]
## 🐛 Bug report
When we kill princess Moira before emperor thaurissan in brd, she does not give any loot except some silver.

### Expected behavior
She should drop some blue items when she is killed before emperor thaurissan.

### Steps to reproduce
1. Go to brd
2. Kill princess while thaurissan still lives
3. Loot her and see that you do not get the loot.

**Comment by SoloCraftServer** [comment]
![image](https://github.com/SoloCraftServer/bugtracker/assets/116836123/2c0bfd5f-b3ea-43a4-b606-1383dff7f4e9)
