### ISSUE TITLE
Onyxia' Liar Door - Object is in Motion

### ISSUE THREAD

**Issue by Wolfsoka79** [SoloCraftServer/bugtracker#185]
## 🐛 Bug report
When trying to enter Onxyia's Liar the last 2 days, when i click on the door to open i'm getting the message "Object is in Motion"

### Expected behavior
Door should open.

### Steps to reproduce
1. Just click on the door.
2.
3.

**Comment by SoloCraftServer** [comment]
It works fine for me and all other players. Do you have custom patches?

**Comment by Wolfsoka79** [comment]
You are correct! I discovered tonight that the 1.14.2 client I am running is causing this. Loaded 1.12 and had no issue. Thank You!!Sent from my iPhoneOn Mar 21, 2024, at 12:32 PM, Solo ***@***.***> wrote:﻿
It works fine for me and all other players. Do you have custom patches?
