### ISSUE TITLE
Southshore Guards do not fight Shadowy Assassins

### ISSUE THREAD

**Issue by necropola** [SoloCraftServer/bugtracker#186]
This has been reported on the **vMangos** bug tracker as https://github.com/vmangos/core/issues/1657 and has apparently been fixed trough https://github.com/vmangos/core/pull/1630 which may or may not have been merged to SoloCraft.

It looks like the fix has been implemented as a **Faction Change (Event)**: https://github.com/vmangos/core/pull/1630/files#diff-fa8449b336dbb842bbfc6e6f6b3783242d56f253342b4435e26d85d979ff2dd0R408-R418

Anyway, on SoloCraft the Southshore Guards are currently ignoring the attacking [Shadowy Assassins](https://www.wowhead.com/classic/npc=2434/shadowy-assassin#comments), but they clearly should engage as pointed out in the comment section on Wowhead, e. g. by [this comment](https://www.wowhead.com/classic/npc=2434/shadowy-assassin#comments:id=4278)
> Unless you have great reflexes, it takes a bit of time to manage to "tap" one of these, so that you can loot it, before the Southshore guards bring them down ...

**Comment by SoloCraftServer** [comment]
Fixed after next restart, I'll close this once its live.
