### ISSUE TITLE
.partybot pause should remove auto attack

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#19]
## 🐛 Bug report
.partybot pause 

This command should also make party bot stopcasting/attacking. I try to use this command on blood lord mandokir to stop the watched target to attack. I also tried to use .partybot attackstop but all my bots stop attacking then. Using .partybot attackstart do make my bots attack even the paused ones :)

Does not make the 

### Expected behavior
A paused bot must stop casting/buffing/auto attack
### Steps to reproduce
1. Send bot to attack a target
2. Use .partybot pause on a targeted bot
3. The bot wont stop auto attack/casting

**Comment by SoloCraftServer** [comment]
Fixed on PTR, I'll close the case once it is pushed to live.
