### ISSUE TITLE
Bug: Druids may move at Feline speed while in Caster form after login/spawn 

### ISSUE THREAD

**Issue by necropola** [SoloCraftServer/bugtracker#190]
## Bug
I have two Druids on SoloCraft, a Feral Druid (A) with the `Feline Swiftness` talent and a Balance Druid (B) without it. When I log into Druid (A) in an outdoor area (capital city) she runs at Feline Speed while in Caster form, until she goes somehwere indoors (or switches forms). The same does not happen on Druid (B).

I've also seen Druid bots (at higher level, even Healers) being spawned with increased movement speed, i. e. they kinda run ahead and have to constantly stop running in order to stay with the player. 

My guess is that the speed increase from the `Feline Swiftness` talent is applied on login/spawn without checking for the form/stance first.

The only issue/commit I could find in vMangos/core which may be related is the following, but my gut feeling is that this issue probably only exists on SoloCraft and not in vMangos/core:
- Issue: https://github.com/vmangos/core/issues/1577
- Fix: https://github.com/vmangos/core/commit/2bf4c58f38d394889e6da322a71b00f00aa5950c

**Comment by SoloCraftServer** [comment]
The "fix" you've provided has nothing to do with this (is also already in our core). Thanks anyway. I'll take a look soon

**Comment by necropola** [comment]
Hence I wrote "maybe related" .
