### ISSUE TITLE
Healers are not cleansing poisons/mind controls and are not healing DPS

### ISSUE THREAD

**Issue by Bob-Weaver** [SoloCraftServer/bugtracker#193]
I am trying to solo Hakkar using the same strategy that I have used to kill him multiple times (2 Warrior Tanks, 5 Paladin Healers, 12 Rogue DPS). This time, however, my Paladin healers are not cleansing poisons/mind control and are not healing the DPS which is leading to them dying from AoE damage.
Rather than cleansing poison, they stand there attempting to heal through the poison damage. During the boss fight, they appear to be glitching and targeting randomly instead of casting heals on the raid. I have tried swapping the Paladins for Priest healers and still got the same problem.

**Comment by SoloCraftServer** [comment]
Everything is the same, we didn't touch or edit any scripts. Make sure you put them in seperate groups.

**Comment by Bob-Weaver** [comment]
I have tried that. Please take a look if you can, there is no reason to be wiping on this boss with VIP especially considering that I have done it this same exact way numerous times and it is no longer working. The healers are literally standing there doing nothing instead of healing raiders that are taking damage. And yes, this is after using the Unpause All command to be sure.
