### ISSUE TITLE
Killing Nathanos Blighcaller in EPL

### ISSUE THREAD

**Issue by 2024christos2024** [SoloCraftServer/bugtracker#194]
## 🐛 Bug report
I need to kill Nathanos Blightcaller in EPL and demands a raid but i cant create one because game doesnt allow me to do so because its in the out world and not inside a dungeon or a raid. How i will complete this quest? He cant be killed in 5 man group. The quest its Order must be Restored 

### Steps to reproduce
1.
2.
3.

**Comment by 2024christos2024** [comment]
It concerns the quest Order must be  Restored

**Comment by SoloCraftServer** [comment]
https://www.wowhead.com/classic/npc=11878/nathanos-blightcaller#comments:id=2913651
