### ISSUE TITLE
Bug: Eye of Kilrogg left-overs

### ISSUE THREAD

**Issue by necropola** [SoloCraftServer/bugtracker#195]
- Summon an **Eye of Kilrogg** on your Warlock
- Wait until it despawns (do not cancel it)
- Log out
- Log back in on same character or another
- Observe that an **Eye of Kilrogg** is spawned at the location where your Warlock stood when she spawned it

According to Guild Chat this (left-over Eyes of Kilrogg in and around capitals) isn't a new observation, but I could not find a bug report. Hope this helps to fix it, since it's now documented how to reproduce.

**Comment by SoloCraftServer** [comment]
Tested in 1.12 several times and cannot reproduce it.

**Comment by SoloCraftServer** [comment]
Confirmed now
