### ISSUE TITLE
The Quest "Collection of Goods" for the Human Paladin Lv60 mount will not complete.

### ISSUE THREAD

**Issue by Krogsly** [SoloCraftServer/bugtracker#199]
## 🐛 Bug report
 The Quest "Collection of Goods" for the Human Paladin Lv60 mount will not complete. I have all the materials, but the NPC is not accepting completion

### Steps to reproduce

https://github.com/SoloCraftServer/bugtracker/assets/175260488/9b74ddd7-0d16-42a1-b2cb-74ef2289b288

1.
2.
3.

**Comment by SoloCraftServer** [comment]
Close your game and clear your WDB folder (cache files)

**Comment by Krogsly** [comment]
Completed. Thank you!
