### ISSUE TITLE
"Manhunt quest doesn't show other reward"

### ISSUE THREAD

**Issue by wolfcarnage** [SoloCraftServer/bugtracker#2]
## 🐛 Bug report
Just start the quest "Manhunt"

### Expected behavior
When speaking to the quest giver it shows the bracers but it doesn't say the stats or the name, in the quest log it's completely empty
![image](https://user-images.githubusercontent.com/117287320/199505062-c331450d-f18d-4398-9723-b73403421fab.png)

### Steps to reproduce
1.Complete "Collector"
2.Start or speak to the quest giver that gives the quest "Manhunt"

**Comment by SoloCraftServer** [comment]
![image](https://user-images.githubusercontent.com/116836123/199570545-8c54f840-e140-4f54-86b2-e262aa56388e.png)
It works fine to me, try clearing your cache files (close wow first before you do)
