### ISSUE TITLE
Mother's Milk Quest bug

### ISSUE THREAD

**Issue by KingKonna** [SoloCraftServer/bugtracker#204]
## 🐛 Bug report
Trying to complete the quest Mother's Milk. In this quest you're supposed to get poisoned with the poison 'Mother's Milk' which is applied by the LBRS boss Mother Smolderweb. Right now, I am unable to complete this quest because the quest giver Ragged John doesn't have the necessary dialogue option ("Milk me, John!") required to trigger the completion of the quest objective. I am poisoned with Mother's Milk while talking to Ragged John. So the quest is not working as intended. I have tried abandoning the quest and accepting it again, but for some reason Ragged John doesn't recognize that you are poisoned.

### Expected behavior
When your character is poisoned by Mother's Milk debuff. Ragged John should have an dialogue option: "Milk me, John!" which should complete the quest objective. Allowing you to finish the quest.

Quest details: https://www.wowhead.com/classic/quest=4866/mothers-milk
Youtube video of the quest turn in: https://youtu.be/z1xa943Ofxg?t=522

### Steps to reproduce
1. Get the quest Mother's Milk from Ragged John.
2. Go to LBRS, engage Mother Smolderweb and let her apply the Mother's Milk poison debuff on you.
3. Return to Ragged John and try to complete the quest.

**Comment by KingKonna** [comment]
Clarifying that I am using the 1.12.1 client.

**Comment by SoloCraftServer** [comment]
https://github.com/SoloCraftServer/bugtracker/issues/172

**Comment by KingKonna** [comment]
> #172

I don't know if this as issue just on my end. I am aware that this bug has been reported before and you weren't able to reproduce it at the time. I am not sure what means you used when you attempted to reproduce it. Whether you simply used commands to apply the debuff on you and turned in or whether you actually went out of your way to actually go into the dungeon and get the debuff the intended way. Anyway, the bug is real and I and perhaps some other people are unable to finish the quest. I uploaded personal footage on a burner account where you can see the full run of the quest. From the quest accepting, to the end. Speeding up the boring parts of course.

Here's the link: https://youtu.be/4MC9LRo1usg
