### ISSUE TITLE
Character damage bug

### ISSUE THREAD

**Issue by Fanthos123** [SoloCraftServer/bugtracker#206]
## 🐛 Bug report
Character 'Fanthos' damage is halved in melee and ranged. All abilities do about half the expected damage to all mob types, cloth plate ect.

### Expected behavior
-My ranged attack is 387-477. Expect auto attack damage is 387-477 +/- Armor effects. Damage Output is typically half of 387-477. My ranged attacks hit for 200-240 damage, which is well under what my UI is saying.
-My ability aimed shot adds 600 damage to my (base) attack. When used on a normal spider at level 55, I will hit the mob for about 607 damage(non-crit). Normally a tier 3 hunter would  do 1200-2k damage aimed shot depending on the crit.
-My multishot which adds +150 damage to my ranged attack hits for only 368 damage. That is very low for a tier 3 hunter.

### Steps to reproduce
1. Take the character and compare the damage output to the expected results.
2. Switched out my weapons and the result is lower than stated weapon damage.
3. Verified there is no visible debuffs on the character, no rez sickness ect.

**Comment by Fanthos123** [comment]
![WoWScrnShot_072724_180603](https://github.com/user-attachments/assets/e47ade60-fd78-4bb4-a0e6-708a8002e5d0)

Aimed Shot damage.

**Comment by Fanthos123** [comment]
![WoWScrnShot_072724_180715](https://github.com/user-attachments/assets/6f91d750-8227-4292-a724-f7120c9084cf)
Multi-shot Damage.

**Comment by Fanthos123** [comment]
![WoWScrnShot_072724_181833](https://github.com/user-attachments/assets/bacb7e12-0ce4-4e86-b4b6-26a299fe5686)
Regular shoot damage with expected numbers highlighted. I know armor reduces the damage, but not that much??

**Comment by Fanthos123** [comment]
I did switch to Marksman to make the damage seem better. But for tier 3 it definately does feel lower than it should. Thanks for checking. I have another character on a very old realm that is only tier 2. full 8/8 and it does way more single target damage.

**Comment by SoloCraftServer** [comment]
It says ranged power 0 on your screenshots. You give 0 detail, no logs. I logged into your character on local and have 1362 power.

![image](https://github.com/user-attachments/assets/3d6cbc84-44f9-41df-8921-dfcc0a261a26)
