### ISSUE TITLE
Targeting Bug

### ISSUE THREAD

**Issue by Phillipjn** [SoloCraftServer/bugtracker#207]
## 🐛 Bug report
I am trying to make a bot stay, but it isn't staying and instead it selects a member i haven't even clicked on. So, i have to click a new target, then the target i want to have stay/move/remove instead of the original target i selected.

### Expected behavior
This is what is happening. Kinda odd that its happening, when it was fine 1 day ago. : https://www.youtube.com/watch?v=BY905GjdIss

### Steps to reproduce
1. Telling bots to come to me, but its selecting a target i never clicked.
2. using the stay command makes a different target stay.
3. Clicking a target and using partybot commands, selects a different target i never clicked on.

**Comment by SoloCraftServer** [comment]
Seems like this is only happening on the 1.14 client, I'll check it soon

**Comment by Phillipjn** [comment]
It's happening when i mouse over one of the bots and issue the commands and then it targets them instead of the one i have click targeted. 

So, if i hover mouse over one of the bots. It issues the commands to the one i am hovering over with my mouse.

It's been happening for 4 days now.

**Comment by SoloCraftServer** [comment]
I can't reproduce it

**Comment by SoloCraftServer** [comment]
Disable Honorspy addon and try again

**Comment by Phillipjn** [comment]
Works fine now. its honorspy

**Comment by Fanthos123** [comment]
Confirmed honorspy, i had the same issue. This also caused you to add bots to your friends list.
