### ISSUE TITLE
Shaman's talent of reducing the wolf's casting time, only reduces it by half

### ISSUE THREAD

**Issue by munash1** [SoloCraftServer/bugtracker#208]
[##](![imagen_2024-07-30_003525588](https://github.com/user-attachments/assets/d9e4a7e4-177d-4b59-8fc4-e8c9713086a7)) 🐛 Bug report

![imagen_2024-07-30_003550251](https://github.com/user-attachments/assets/55b2d837-6e18-49e1-bf07-b55e23d5d149)
Shaman's talent of reducing the wolf's casting time, only reduces it by half
### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
Ghost Wolf = 3 secs cast. 2/2 Talent = -2 and the spell becomes 1 sec cast (which is the case here)
