### ISSUE TITLE
.partybot attackstart

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#21]
## 🐛 Bug report
There is a command I quite use often .partybot attackstart. Ideal for switching targets.

I would suggest that when using .partybot attackstart healers should not rush melee to auto attack boss/target, that could lead to their death. Ex fighting Rend in UBRS can be deadly with his cleaves :D (not so much now the raid is caped at 15man, anyway, let's say magmaddar or baron geddon).

### Expected behavior
This command shouldn't send healer to auto attack at melee, because this is not a natural behaviour for healers. It should work a the same way the "auto attack" skill sends bots to fight with healers remaining passive in follow/heal mode and be used for switching targets.

### Steps to reproduce
1. Use command .partybot attackstart
2. Healers will run to melee, eventually will stop when healing needs to be done, then continue to walk towards target

**Comment by SoloCraftServer** [comment]
Fixed, will be pushed tomorrow
