### ISSUE TITLE
Pip's Skinner [12709] doesn't function as a Skinning Kife

### ISSUE THREAD

**Issue by Doxorn** [SoloCraftServer/bugtracker#217]
## 🐛 Bug report
The item Pip's Skinner does not function as a skinning knife
https://www.wowhead.com/classic/item=12709/pips-skinner

### Expected behavior
It should function as a skinning knife as well. It is in it's flavor text. As well as said multiple times in the wowhead link comments

### Steps to reproduce
1. Have Pip's Skinner in your inventory
2. Do not have a Skinning Knife in your inventory
3. Try to skin an animal

**Comment by SoloCraftServer** [comment]
![image](https://github.com/user-attachments/assets/7035351d-2604-4969-ba1f-23d9c77f8ab8)
