### ISSUE TITLE
Totems bot shaman

### ISSUE THREAD

**Issue by fantaghiro92** [SoloCraftServer/bugtracker#22]
I want to report that bot shamans at level 60 no longer cast totems.

I don't know if it's intentional but it would be nice if they did.

Thanks for what you do, good job

**Comment by SoloCraftServer** [comment]
They do cast totems.

![image](https://user-images.githubusercontent.com/116836123/204173175-98ff2749-6392-4b86-8270-25d10eef0651.png)


Where did it happen and what was the role of the shaman?

**Comment by fantaghiro92** [comment]
Thank you for your quick answer.
Up to level 59 bots cast totems, at level 60 they no longer cast them.
The role was rest shaman.

**Comment by SoloCraftServer** [comment]
![image](https://user-images.githubusercontent.com/116836123/204322188-0cbaa8d2-51ad-4083-a641-45c532c67103.png)
I can't reproduce it, they do spawn totems once they enter combat.

**Comment by fantaghiro92** [comment]
![Screen](https://user-images.githubusercontent.com/119170378/204336286-48262afc-eaee-48bf-8f35-83038d242191.jpg)

I asked some horde players and they all confirmed that totems at level 60 don't work.
I am attaching a screen I made with 4 shamans, as you can see they don't even cast a totem while they are in combat
