### ISSUE TITLE
Stuck on Journeyman Tailoring

### ISSUE THREAD

**Issue by Nosscire1997** [SoloCraftServer/bugtracker#220]
## 🐛 Bug report
Unable to learn Apprentice Tailoring, It says i already know it but my Tailoring maximum is still 75 points

### Expected behavior
should be able to learn from 50 points in tailoring

### Steps to reproduce
1. create a character, reach level 5 
2. level tailoring
3. try to learn apprentice

**Comment by SoloCraftServer** [comment]
It works perfectly fine. Close the game and clear your cache files (WDB folder) or download our 1.12 client
