### ISSUE TITLE
Disease dispell on Heigan fight

### ISSUE THREAD

**Issue by morino92** [SoloCraftServer/bugtracker#225]
## 🐛 Bug report
Priest dispell Disease just one time during a fight.

### Expected behavior
Priest should dispells Disease during the fight, like paladin. Maybe create a command for prio dispells.

### Steps to reproduce
1. Fight Heigan on horde side = very Hard 
2.  Fight Heigan on Alliance side = very easy
3.

**Comment by SoloCraftServer** [comment]
Updated the logic
