### ISSUE TITLE
Broken Dream Catcher Quest

### ISSUE THREAD

**Issue by ivaninski** [SoloCraftServer/bugtracker#226]
## 🐛 Bug report
The Ferocitas the Dream Eater quest in Teldrasil (Kill 7 Gnarlpine Mystics and get Tallonkai's Jewel) can never be completed, because the game does not register your Gnarlpine Mystic kills.

### Expected behavior
each time you kill a Gnarlpine Mystic you should get credit for the kill toward completing the quest

### Steps to reproduce
1.  Obtain the Ferocitas the Dream Eater quest by turning in the empty locket in the Dream Catcher quest line for a night elf in Dolaran.
2.  Try to kill a Gnarlpine Mystic
3.  Successfully kill a Gnarlpine Mystic and watch your counter stay still at 0.

**Comment by ivaninski** [comment]
Here I am starting the fight with a Gnarlpine Mystic
![start-fight](https://github.com/user-attachments/assets/41ac832a-b0fb-4633-944c-567621b94844)

Here I am after killing the Gnarlpine Mystic but my "kill count" is still at zero.
![mystic-slain-but-no-credit](https://github.com/user-attachments/assets/c48c1d85-c1b2-4828-896d-cc0f887ff3f1)

**Comment by SoloCraftServer** [comment]
![image](https://github.com/user-attachments/assets/c3b35b44-b31e-43e5-be9b-9f31bd3caf31)
