### ISSUE TITLE
Healer bots do not cleanse poison or disease effects

### ISSUE THREAD

**Issue by mw108** [SoloCraftServer/bugtracker#229]
## 🐛 Bug report
When any party member is affected by a poison or disease effect, Healers don't cleanse it even though the are capable of.

### Expected behavior
Healers should cleanse poison or disease status effects.

### Steps to reproduce
1. Add players to your party including a Healer like a Priest or Shaman.
2. Get a party member affected by a disease or poison effect.
3. Healers do not remove the effect.

**Comment by SoloCraftServer** [comment]
They do. Make sure you put 1 healer in each group.

**Comment by mw108** [comment]
From what I've seen they don't.

### Disease ###

https://youtu.be/-Of1tP4D53I

### Poison ###

https://youtu.be/9VPqQGb7Ds4

**Comment by SoloCraftServer** [comment]
You said healers but it seems to be shaman only

**Comment by SoloCraftServer** [comment]
I'll fix it thanks
