### ISSUE TITLE
Disconects in AV or other battlegrounds

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#23]
## 🐛 Bug report

Was auto walking in stealth while chatting in guild when this happened. 

![image](https://user-images.githubusercontent.com/15770932/204149762-78aec8ba-f0c2-4caa-b4a0-948d56b2bfde.png)

However, when i log back in, i have deserter... after 40min av.

### Expected behavior
Wow errors can occur but let us log back in in the same BG without getting deserter debuff :(

**Comment by SoloCraftServer** [comment]
This is more like a client issue, its not the server that is kicking you.

![image](https://user-images.githubusercontent.com/116836123/204172957-49e78759-c402-4fdb-b86c-b16abb58de0b.png)
