### ISSUE TITLE
Epic mounts for sale incorrectly state lvl 40 required until after purchase. 

### ISSUE THREAD

**Issue by mtvander** [SoloCraftServer/bugtracker#230]
## 🐛 Bug report

Before purchasing an epic mount, the hover information states that it only requires lvl 40 to use. Once purchased, the mount can't be used until lvl 60. Aplatfter the mount is purchase, the hover information correctly states that lvl 60 is required. (I don't know if this makes a difference, but I bought the mount at level 40 before I purchased the riding skill training. I tried using the mount before and after I bought the training.) Sometimes after logging in, the mount info again says lvl 40 is required, but when attempting to use it, there is an error message that says that my skill level isn't high enough.

Info says level 40 is required, but not usable.
![mount 40 Screenshot 2024-11-03 194924](https://github.com/user-attachments/assets/375cf04c-8908-438e-a392-30f6504c3274)

Info says level 40 is required, but not usable.
![mount 60 Screenshot 2024-11-03 195046](https://github.com/user-attachments/assets/67cef825-c8b7-4745-a51c-83a7851547d9)

### Expected behavior

Epic mounts should correctly state that lvl 60 is required for use, or the epic mount should be usable at lvl. 40.

### Steps to reproduce

1. Be level 40.
2. Go to Katie Hunter.
3. Buy Epic Mount (e.g. Swift White Steed).
4. Buy riding training from Randal Hunter.
5. Try to use Epic Mount.
6. Get the message "You can't use that item." or "You aren't skilled enough to use that item."
7. Realize you have wasted your gold.

**Comment by SoloCraftServer** [comment]
Clear your cache files.

**Comment by mtvander** [comment]
Thanks for the recommendation. I deleted cache files in '-classic_era_' folder. Relaunched game. It still doesn't work. Any other suggestions are appreciated!

**Comment by mtvander** [comment]
Do you have any other recommendations. I have deleted and redownloaded the 1.12 and 1.14 clients and reinstalled. On both of them I still have this problem. Thank you.

**Comment by mtvander** [comment]
> Clear your cache files.

Do you have any other recommendations? I have deleted and redownloaded the 1.12 and 1.14 clients and reinstalled. On both of them I still have this problem. Thank you.
