### ISSUE TITLE
Scarlet Monastery Graveyard's Illusionary Phantasm

### ISSUE THREAD

**Issue by Moonscarlet** [SoloCraftServer/bugtracker#231]
## 🐛 Bug report
Haunting Phantasms in SM GY can summon Illusionary Phantasms which are supposed to be killed in one hit but they are treated as normal mobs with full HP.

![WowClassic_Q2LoZWum8Q](https://github.com/user-attachments/assets/3716f1df-d9a4-4112-be4b-5e68ec7a7df1)

### Expected behavior
They should die in one hit.

### Steps to reproduce
1. Go to Scarlet Monastery's Graveyard side
2. Fight Haunting Phantasms

**Comment by SoloCraftServer** [comment]
https://www.wowhead.com/classic/npc=6493/illusionary-phantasm#drops;mode:normal

**Comment by Moonscarlet** [comment]
> https://www.wowhead.com/classic/npc=6493/illusionary-phantasm#drops;mode:normal

I don't know what your comment means as you didn't clarify anything but that mob dies in 1 hit or any single targetted spell in wow so that is a bug here! 
If you intentionally made it not like that in your server and changed it to act as a normal mob then sure.
