### ISSUE TITLE
Warlock epic mount quest, breaks near the end of the chain and can't complete.

### ISSUE THREAD

**Issue by nzkritik** [SoloCraftServer/bugtracker#232]
## 🐛 Bug report
I recently levelled to 60 and started the quest line to get the epic mount for warlocks.
After completing the quest [Xorothian Stardust](https://www.wowhead.com/classic/quest=7625/xorothian-stardust), I accepted the next quest in the chain, [Imp Delivery](https://www.wowhead.com/classic/quest=7629/imp-delivery). However, I didn't get the quest item in my inventory, the quest didn't show up in my quest log, and I can't get it again from the quest vendor.

### Expected behavior
I should be able to take the quest "Imp Delivery" and I should get the quest item needed for the quest

### Steps to reproduce
1. progress through the quest chain to "Imp Delivery" quest
2. Accept quest "Imp Delivery"

**Comment by Kekwaitlmao** [comment]
I completed the whole questline, including the ones mentioned, 1 week ago, no issues at all. 
Are you sure you completed all the pre-quests to enable "Imp Delivery" one? 

Sounds like you did not, hence this issue.

**Comment by nzkritik** [comment]
I was offered and accepted the quest, but it did not show up in my quest log, and there didn't appear to be a way to get it again.

I guess I'll have to buy and ride a crappy horse :(

**Comment by nzkritik** [comment]
I am closing this issue, as it appears only to effect me.
