### ISSUE TITLE
Specialization of Engineering

### ISSUE THREAD

**Issue by Donken6** [SoloCraftServer/bugtracker#235]
## 🐛 Bug report
 
![WoWScrnShot_112124_222336](https://github.com/user-attachments/assets/1868a2d1-0c55-47c7-b3e6-47446584971c)
![WoWScrnShot_112124_222301](https://github.com/user-attachments/assets/83060073-46ad-4c2f-ba2c-0a1f1dadd99b)

### Expected behavior
 I should be able to specialize in either gnomish or goblin engineering from this trainer according to wowhead:: https://www.wowhead.com/quest=29477/gnomish-engineering#comments
I tried this at lvl 60 and as you can see Im far high enough skill lvl, but npc wont give me quest.
### Steps to reproduce
1. turn 60
2. lvl engineeing to atleasst 200
3. speak with Roxxix in Orgrimmar (artisan trainer)

**Comment by SoloCraftServer** [comment]
Look for the classic version, this quest was added in patch 4.3.0
