### ISSUE TITLE
Magistrate Sevren quest from Brill - Graverobbers, is not counting the kills for rot hide robbers

### ISSUE THREAD

**Issue by Keoman26** [SoloCraftServer/bugtracker#236]
### Steps to reproduce
1. Take the quest, start kiling gnolls and watch the counter by pressing L, not questie, questie is not counting also. I think this is normal because the wow database is not updating on this quest
2. I am using the 1.14 client version, i did not tried on 1.12.1
3. Thank you!

**Comment by RONBELICO** [comment]
i can complete with ver 1.12
