### ISSUE TITLE
Bought faction change for my lvl 60 orc warrior.

### ISSUE THREAD

**Issue by Wulfgrym** [SoloCraftServer/bugtracker#238]
## 🐛 Bug report
Simply, I bought the faction swap. I was unable to collect it from the mailbox on my warrior. i hit the return button and its gone of course, so im not sure if its recoverable or not.

### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
Please open a ticket on discord and let me know your character name.
