### ISSUE TITLE
Druid boost

### ISSUE THREAD

**Issue by talminer** [SoloCraftServer/bugtracker#24]
## 🐛 Bug report
Boosted the druid to 60 and have cat and travel form, but I don't have the other forms.

wow character name is Yogibear

**Comment by SoloCraftServer** [comment]
Hello, the boost contains levels and training for gold only.

**Comment by talminer** [comment]
@SoloCraftServer, if this is the case, then why did you assist a friend with getting their totems for a shaman after a boost?
