### ISSUE TITLE
My hunter pet disapears on log out

### ISSUE THREAD

**Issue by Std111** [SoloCraftServer/bugtracker#242]
## 🐛 Bug report
So yesterday i started a hunter and did my pet quests to be able to tame a pet but 2 diffrent times after getting my pet when i logged out and then back in my new pet was gone and call pet did nothing 

### Expected behavior
After taming a pet it should be perminent thru log offs, call pet should make my pet appear, i shouldnt have to go tame a new pet

### Steps to reproduce
1.tame a pet
2.when your new pet is tamed log out
3.log back in and find your new pet is gone, try the call pet command and no pet comes

**Comment by SoloCraftServer** [comment]
They are working fine, make sure you feed them well.
