### ISSUE TITLE
Bots drinking in begining of the fight

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#25]
## 🐛 Bug report
When monsters are pulled in dungeon by a tank or by mistake, healers wont stop drinking to heal party members. After they finish drinking, if some random player or player bot did die, they chose to start ressing instead of healing the players in fight. 

### Expected behavior
When a player/player bot enter in combat, all healers should act like if they are in combat and should trigger their healing mode.

### Steps to reproduce
1. Aggro monsters with tank while bots are drinking
2. Healers will continue to drink

**Comment by SoloCraftServer** [comment]
Tested it several times, This only happens when the healer is out of rage (it's following the party leader). Make sure the healers are in range to heal the party members.
