### ISSUE TITLE
Bot shamans do not cast totems

### ISSUE THREAD

**Issue by fantaghiro92** [SoloCraftServer/bugtracker#29]
In reference to my old ticket, I solicit the problem:
- I want to report that bot shamans at level 60 no longer cast totems.

I asked some horde players and they all confirmed that totems at level 60 don't work.
I am attaching a screen I made with 4 shamans, as you can see they don't even cast a totem while they are in combat.

https://user-images.githubusercontent.com/119170378/204336286-48262afc-eaee-48bf-8f35-83038d242191.jpg

I hope it can be resolved because having totems in dungeons is essential for the horde.
Thank you

**Comment by SoloCraftServer** [comment]
They work fine, they just won't cast it at 100% HP or mana or when not in combat. 

https://github.com/SoloCraftServer/bugtracker/issues/22

**Comment by fantaghiro92** [comment]
No they don't even cast a totem. The whole community confirms it.
I attach another screen where you can see that the shaman in combat and with mana and life lower than 100% does not cast the totems.
I hope it's a fixable problem.
![Screen](https://user-images.githubusercontent.com/119170378/205460993-066a8f4a-59af-4297-9080-f40fdcaab6ca.jpg)
