### ISSUE TITLE
Scholomance, Lorekeeper Polkelt

### ISSUE THREAD

**Issue by sadpanda2** [SoloCraftServer/bugtracker#30]
After entering the Lorekeeper Polkelt room the gate closed behind me. Killing all mobs + boss inside did not open the gate.... i was stuck.

i think i used .partybot usegobject macro by accident near the gate  and it somehow made the gate close.

**Comment by SoloCraftServer** [comment]
Hello, if you closed it by mistake with the command, you should be re-open it with the command again :)
