### ISSUE TITLE
Further reminder bugged shamans

### ISSUE THREAD

**Issue by fantaghiro92** [SoloCraftServer/bugtracker#31]
They don't even cast a totem. The whole community confirms it.
I attach another screen where you can see that the shaman in combat and with mana and life lower than 100% does not cast the totems.
I hope it's a fixable problem.
![Screen](https://user-images.githubusercontent.com/119170378/205461243-4a8c0a01-489b-4e3c-a9e1-97a395e1a85d.jpg)

**Comment by SoloCraftServer** [comment]
Confirmed, they don't spawn on "non vip" accounts at level 60
