### ISSUE TITLE
Caster DPS wierd behaviours in raid

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#32]
## 🐛 Bug report
To followup the post : https://github.com/SoloCraftServer/bugtracker/issues/26 I recorded several videos showing why, in raid, casters cant have slow range - 20m for mages because they want to use fire blast - and use auto attack.

Here I'm trying to get the casters to come towards me 30 yards from the boss to avoid the boss' area silence. However, the casters return to 20 meters to cast and are vulnerable to the silence of the boss. 

Exemple with bat boss in ZG : https://streamable.com/0185lv

In this other example, in MC I use magmaddar fear to spread my bots, and limit the AOE damage, there is the range problem as stated above and the fact they want to melee dps, getting fatally close to the boss and stacked. 

Magmaddar in MC : https://streamable.com/ytd003 and https://streamable.com/epg8ot

The third exemple would be Shazzrah in MC to keep the range group out of the arcane explosion range but I coudn't record this boss.

### Expected behavior
In raid only, allow mages to stand max range and avoid using fireblast or any under 30 yards spell. Also remove auto attack action on them. Keep them wanding at 5% mana this is fine.

**Comment by SoloCraftServer** [comment]
This is probably related to https://forum.solocraft.org/viewtopic.php?t=101
The ranged dps were pulling mobs before while running away from aggro, so it was removed to prevent that.

I'll find a solution for this problem

**Comment by SoloCraftServer** [comment]
Made some changes regarding this, I will close the issue once its pushed to live.
Please let me know if there are issues.

**Comment by Rasuru2** [comment]
@SoloCraftServer this hasn't been resolved. Mages are still running within 20 yards and using auto attacks.
