### ISSUE TITLE
Casters drinking in fight (sometimes)

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#33]
## 🐛 Bug report
On this ZG boss, after P2 transition, bots decided to drink in the middle of the fight :D

https://streamable.com/ixhflr

### Expected behavior
Well, wake up those lasy peons :D

**Comment by SoloCraftServer** [comment]
Some bots probably get out of combat after P1, this is actually not a bug, you should let them start attack with the command or from the addon :)
