### ISSUE TITLE
Healers heals range

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#34]
## 🐛 Bug report
In addition to this other [post](https://github.com/SoloCraftServer/bugtracker/issues/32), healers do not seem to use their healing spells from 40 meters range.

See the video here : https://streamable.com/2v8x8h

### Expected behavior
Healers should start heal at 40 yard range ;)

**Comment by SoloCraftServer** [comment]
Healing is changed into 40 yards but keep in mind dispel/decurse is 30 yards
