### ISSUE TITLE
Issue with  Quest in WPL

### ISSUE THREAD

**Issue by Danny486** [SoloCraftServer/bugtracker#35]
Quest: Counting Out of Time cannot be completed

Collecting 5 Andorhal Watches found in lockboxes ammongst Ruins of Andorhal...

### Expected behavior
Lockboxes cannot  be open (Invalid target)

### Steps to reproduce
1.Running around and trying open different Lock boxes  (Invalid target)
2. Leaving  party with  bots  and trying to open lockboxes (Invalid target)
3. Abborting Quest and accept quest again
4. trying once again to open Lock Boxes  but cannot be open  (Invalid target)
![Unbenannt](https://user-images.githubusercontent.com/118528874/207586304-00f5e79b-c2e3-4fba-aa12-20a35f6469c1.PNG)

**Comment by SoloCraftServer** [comment]
Can't reproduce, it works fine to me. I suggest you to close wow and clear your cache files (WDB folder)

![image](https://user-images.githubusercontent.com/116836123/208242358-fe090b97-ac3d-41e1-9acb-d019c84a6fad.png)
