### ISSUE TITLE
Body and Heart (Alliance Night Elf Druid bear quest)

### ISSUE THREAD

**Issue by DandyHi** [SoloCraftServer/bugtracker#36]
## 🐛 Bug report
Lunaclaw appearing after using the Cenarion Moondust near the Moonkin Stone of Auberdine, but suddenly disappear without giving time to fight or interact...

### Expected behavior
(https://www.youtube.com/watch?v=BqdezeT0fQg)

### Steps to reproduce
1. Create a Night Elf
2. Start the quest Body And Heart
3. Summon Lunaclaw at Moonkin Stone

**Comment by SoloCraftServer** [comment]
Was bugged after todays restart, it works now.
