### ISSUE TITLE
problem with hunter's pet

### ISSUE THREAD

**Issue by Dhonesbr** [SoloCraftServer/bugtracker#38]
Expected the hunter's pet disappears after a while, after he passes a level or in a certain period of time, he also does not attack when starting a fight
<!--![Captura de Tela (10)](https://user-images.githubusercontent.com/120841612/208300298-58e05400-e629-48ca-b2e1-91b1f464d4a7.png)

### Steps to reproduce
1.
2.
3.

**Comment by Dhonesbr** [comment]
![Captura de Tela (10)](https://user-images.githubusercontent.com/120841612/208300401-fa65d8b5-9d6d-460b-ad85-68809e6c077e.png)

**Comment by SoloCraftServer** [comment]
Did you feed your pet? If yes, reopen this issue with more details about the pet.
