### ISSUE TITLE
Quest Reward Gear in Donation Shop -- Available on Level 1 characters

### ISSUE THREAD

**Issue by cowpie1** [SoloCraftServer/bugtracker#39]
## 🐛 Bug report
Basically, there are items that are quest rewards (Dungeon Set 2, Icy Barbed Spear, Ravenholdt Slicer, The Thunderwood Poker, Doomulus Prime, and possibly a few others) that can currently be granted to Level 1 players through the Donation Shop on the website. I'm not sure if this is intentional or not, but it seems that this can drastically alter the balance of low-level PvP once the server becomes more populated.

### Expected behavior
Not sure how this is supposed to be interacting, this is simply a PvP balancing observation.

### Steps to reproduce
1. Support the project through donation
2. Create new character
3. Send items to aforementioned character

**Comment by SoloCraftServer** [comment]
The boxes are now set to level 60
