### ISSUE TITLE
Bot (Shaman Healer/Druid Tank) Function in Open World

### ISSUE THREAD

**Issue by cowpie1** [SoloCraftServer/bugtracker#40]
## 🐛 Bug report
I've noticed that Shaman healers will sit and drink between every cast while out of combat, drastically increasing downtime between pulls. I've also noticed that Bear Tank Druids (While Mounted and Out of Combat) will mount up, go into bear form, then recover mana using food. Repeatedly in an endless loop, forcing them to fall far behind the rest of the party while traveling.

### Expected behavior
The Healers need to prioritize getting the group to full health and using available mana, rather than constantly topping themselves off (be it 1% mana or 10%, they will always drink between casts while out of combat). While the Bear tanks need to only prioritize bear form while dismounted and possibly ignore the initial mana threshold from Shapeshifting, as they will sit and drink immediately after shapeshifting.

### Steps to reproduce
1.Summon Shaman Healer or 1A. Druid Tank
2.Have low HP out of combat 2A. Mount up
3.Observe

**Comment by SoloCraftServer** [comment]
Druid dismounting/drinking & repeating has been fixed.
About the shaman report: all healers do follow the same eat & drink rule. You can always let them enter combat by using "attack/start attack" command.
