### ISSUE TITLE
problem with hunter's pet

### ISSUE THREAD

**Issue by Dhonesbr** [SoloCraftServer/bugtracker#41]
Expected the hunter's pet disappears after a while, after he passes a level or in a certain period of time, he also does not attack when starting a fight
I already fed the pet as soon as I captured it with half an hour of play or less it disappeared I captured 10 pets and fed 3 and 3 minutes and they still disappeared after half an hour.
  <!--![Captura de Tela (10)](https://user-images.githubusercontent.com/120841612/208300298-58e05400-e629-48ca-b2e1-91b1f464d4a7.png)

**Comment by Dhonesbr** [comment]
you can see the problem very quickly, just enter the server with a hunter and capture a pet, go in a battle to level it and you will see the bug very quickly. I was disappointed with you guys, I opened a problem here on the forum and you closed it and didn't even solve the problem

**Comment by Dhonesbr** [comment]
if you know there's a problem you have to solve it, don't tell me to rewrite it here

**Comment by SoloCraftServer** [comment]
First of all you don't respect the issue rules, you should follow the template about HOW to report bugs.

We've tested it and it works 100% blizzlike, you should look up for "pet loyalty in classic" for more info. 
And don't tell us what to do, if there is a bug we will fix it.
