### ISSUE TITLE
AQ40 bosses aggro range

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#43]
## 🐛 Bug report
Hello,

In general boss has too high agro range for example satura : 

Here is how it is on classic  : https://www.youtube.com/watch?v=Z3NJTOVusk0&ab_channel=Toke

Bugs, Frankriss and i guess other has huge agro range. 

For satura i would request to put the boss static, without moving around in the room so we have time to position the bots and spread them.

### Expected behavior
Aggro range should be reduced.

**Comment by SoloCraftServer** [comment]
The aggro range for aq20 & aq40 was always large, however I've edited Battleguard Sartura and made it static.
