### ISSUE TITLE
Q: All Along the Watchtowers (Alliance)

### ISSUE THREAD

**Issue by R2WD40** [SoloCraftServer/bugtracker#46]
### Expected behavior

![screenshot](https://user-images.githubusercontent.com/82384480/210178219-47977f12-ea3f-4931-80be-584107b85e19.png)

### Steps to reproduce
1. Go to a watchtower as indicated in https://www.wowhead.com/classic/quest=5097/all-along-the-watchtowers
2. Right-click the 'Beacon Torch'
3. 'The spell is not available to you'

**Comment by kinggoatee** [comment]
I am having same issue on horde side

**Comment by SoloCraftServer** [comment]
Currently set to autocomplete without XP reward until we find the crash cause, if you have this quest, abandon and retake it.
