### ISSUE TITLE
Paladins lay on hands

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#47]
## 🐛 Bug report
Sometimes a seriously wounded bot might be lay on hand by all paladins in the raid. It shouldn't happen in raid. Better let a mage die because he pulled aggro than having 4 oom heal pallys. I would suggest to make lay on hand only used by paladins when their mana is very low. Or they shouldn't use this ability at all in raids.

### Expected behavior
Since bots randomely use this ability I think it is better to remove it's use in raids.

**Comment by SoloCraftServer** [comment]
Atm its scripted to cast it on theirself below 15% HP, same rule applies for party members.

**Comment by SoloCraftServer** [comment]
I can add a rule to make them cast only if the paladin's mana is below 10-20%
