### ISSUE TITLE
Healer targets

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#48]
## 🐛 Bug report
Healers choose to heal the same target at the same time. This leads to a lot of excess heals. For example, four Paladins and four Priests in the same raid will use Holy Light and Greater Healing on the same target. This can cause a lot of wasted healing. 

![image](https://user-images.githubusercontent.com/15770932/210563530-93d23cb8-37df-4c44-aa7e-e0a3225cd7a5.png)

This behavior leads to poor management and performance of heals for bots when it comes to high damage on the entire raid. 

### Expected behavior
Healers should share the priority of heals. For example, healers in group 1 should give priority to healing players in the same group. In the same way that the decurses work, if all the players in the group have their health points at the maximum then the healer of this group can support the others.

**Comment by SoloCraftServer** [comment]
They are scripted not to heal the same target already. Maybe the rule does not apply for the partyleader. I will check it out.
