### ISSUE TITLE
Alliance Traume Quest (First Aid)

### ISSUE THREAD

**Issue by vladimirpyro** [SoloCraftServer/bugtracker#49]
## 🐛 Bug report
Quest link: [Alliance Trauma](https://www.wowhead.com/classic/quest=6625/alliance-trauma#comments)

[Doctor_Gustaf_VanHowzen](https://www.wowhead.com/classic/npc=12939/doctor-gustaf-vanhowzen) does not react even if I met the criteria to complete the quest. 

### Expected behavior
[Doctor_Gustaf_VanHowzen](https://www.wowhead.com/classic/npc=12939/doctor-gustaf-vanhowzen) should react and open a quest screen to allow me to complete quest and give me the next in quest chain: [Triage](https://www.wowhead.com/classic/quest=6624/triage)

My character is lvl 37 and has 225 First Aid skill. 

### Steps to reproduce
1. Get the [Alliance Trauma](https://www.wowhead.com/classic/quest=6625/alliance-trauma#comments) from [Nissa Firestone](https://www.wowhead.com/classic/npc=5150/nissa-firestone)
2. Get yourself to Theramore Isle and find [Doctor_Gustaf_VanHowzen](https://www.wowhead.com/classic/npc=12939/doctor-gustaf-vanhowzen)
3. See if you can complete the quest.

**Comment by SoloCraftServer** [comment]
The quest works fine, retake the quest if you failed it.

**Comment by vladimirpyro** [comment]
I abandoned the quest.
Went back to Ironforge. Took it again.
Traveled to Theramore and Doctor did not react again.

Any suggestions?

**Comment by vladimirpyro** [comment]
[Alliance Trauma.webm](https://user-images.githubusercontent.com/122118396/211147559-c28a345a-8653-4f67-b915-9cbbfe2f4489.webm)

Here you may see it yourself.

**Comment by gnoduyis** [comment]
I am facing the same issue, @vladimirpyro have you eventually able to get this work?

**Comment by vladimirpyro** [comment]
Yes, I have logged out, not Alt + F4. Abandon quest, retake it. Went to theramore and doctor was facing me.
