### ISSUE TITLE
Alterac Valley

### ISSUE THREAD

**Issue by Veldane** [SoloCraftServer/bugtracker#5]
## 🐛 Bug report

Bots endlessly run in a pattern to an from the bunker in Dun Baldar (alliance) and Horde endlessly run from stormpike graveyard to the Dun Baldar bunkers. They do this for hours. 
### Expected behavior

They should try to move forward and take or defend the bunkers
### Steps to reproduce
1. Queue for Alterac
2. Choose the first available instance
3. Go to the Dun Baldar North and South Bunkers

**Comment by Ill-the-rogue** [comment]
Alterac Valley is doable. I have completed 3 AV's in the past 2 hours just fine. Yes it took some understanding how everything moves but realistically there's not really a huge issue with the bots more of an issue with the last boss resetting if there's bots outside each opposing side's "King castle" and drek or van step outside they auto reset.

**Comment by Ill-the-rogue** [comment]
![image](https://user-images.githubusercontent.com/117578818/200174891-b35ae47e-eaaa-44aa-a47c-305dc60bc330.png)
