### ISSUE TITLE
Can't re-enter blackwing lair as ghost

### ISSUE THREAD

**Issue by OleIdole** [SoloCraftServer/bugtracker#51]
## 🐛 Bug report
Unable to click the orb to enter blackwing lair when dead, cannot re-enter raid without ressing at graveyard spirit healer.

### Expected behavior
Should enter blackwing lair as dead when you click the orb or run into it.

### Steps to reproduce
1. Enter blackwing lair
2. Die
3. Corpserun back to blackwing lair entrance
4. Click the orb to re-enter blackwing lair (will not work, this is the problem)

**Comment by Altair484** [comment]
I suspect this bug due to the fact there isn't attune checking when you are alive and there is an attune requirement when dead. I might be wrong but it makes sense to me since the attune removal was a custom making for this server. I think solo can fix it :)

**Comment by SoloCraftServer** [comment]
Once you die in bwl, it will port you at the enterance after next restart, you don't have to click on the orb. This issue will be closed once this fix is live.
