### ISSUE TITLE
Mages using scorch

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#52]
## 🐛 Bug report
Hello, it is not really a bug but a bot behaviour to change. It seems that when the target is bellow 15%, the mages bots start using scorch instead of frostbolt. It may be quite inconvenient when dealing with bosses having high fire resistance in MC or Bwl. Also they do less DPS by using that spell over frostbolt.

### Expected behavior
In raids, mage bots should not use scorch when target is under 15%.

**Comment by SoloCraftServer** [comment]
They use it below 20% HP, what do you suggest? Completely remove it?

**Comment by SoloCraftServer** [comment]
I disabled them using scorch for now, this report will be closed once this change has been pushed on live.

Let me know if it is better without scorch.
