### ISSUE TITLE
Anub'rekhan

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#53]
## 🐛 Bug report
Anub'rekhan boss scarabs does not dispawn after a wipe. Idk if this blizzlike and should be the case.

### Expected behavior
All scarabs should despawn after a wipe

### Steps to reproduce
1. Let several bots die then wipe
2. See some scarabs slowly heading to the first room and patrol there.

**Comment by SoloCraftServer** [comment]
Will be closed once its pushed on live.
