### ISSUE TITLE
Bot rotate on themselves while in "stay" position 

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#54]
## 🐛 Bug report
Sometimes bots won't DPS the target because they are rooted with the .partybot stay command. 
Sine we already spoke about this and if the issue is already solved, kindly close this report :)

### Expected behavior
They should rotate and face the target.

**Comment by OleIdole** [comment]
Can confirm as of yesterday this was still a problem. I had mages rotated away from ragnaros and they would not cast until .move command was used to free them.
