### ISSUE TITLE
Raid disbanded after corpse run in Scholomance

### ISSUE THREAD

**Issue by Etakik** [SoloCraftServer/bugtracker#58]
## 🐛 Bug report
After a wipe and corpse run in Scholomance raid (10 man) disbands after reentering the dungeon which resets the instance. This may also be the case in Stratholme and other dungeons that you can 10 man, but have not tested this.

### Expected behavior
Raid should not be disbanded and instance should not reset after corpse run.

**Comment by SoloCraftServer** [comment]
This was fixed a long time ago. I've tested it a several times and could not reproduce the report.

https://github.com/SoloCraftServer/bugtracker/issues/4
