### ISSUE TITLE
Bots commands should not work on bots from other players.

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#60]
## 🐛 Bug report
Partybots with several real players in the same raid.

Hello, I want to poit out the necessity for certain fight of having two real humans. For example Gothik the harvester. In this fight we have to make two separate group. Me and my mate are calling our own bots. They follow us respectively, That's fine. However the bots commands are beeing executed on all our bots. If I use cometome, the bots of my mate will come. If I use startattack, the bots of my mate will also awnser the call. 
We tryied a lot while in the same raid, the bots was never attacking the good target and acted randomely. **We had to make two separate raid groups inside the same raid zone to manage the killing of the boss.**  Like that the bots was no longer linked together because they are not in the "same" raid and we had full control of them, like it should be :). 

### Expected behavior
Bots command should only be executed on the bots owned/summoned by a player. That way we can better manage complex fights.

**Comment by SoloCraftServer** [comment]
The partybots are scripted like that. They only accept orders from the party leader only.
