### ISSUE TITLE
Quest "Seal of Ascension" can't be completed.

### ISSUE THREAD

**Issue by Casandy** [SoloCraftServer/bugtracker#63]
## 🐛 Bug report

Quest "Seal of Ascension" required for UBRS key can't be completed. If you try to turn it in, the NPC will open the dialog as if you don't have the required item.
![image](https://user-images.githubusercontent.com/72492963/214049317-da8d4621-9f43-4935-b4dc-16099cb35f8c.png)

### Expected behavior

The quest should be able to be completed after you get Forged Seal of Ascension item.
### Steps to reproduce
1. Get Seal of Ascension quest from Vaelan in LBRS.
2. Go to Dustwallow Marsh and use the items provided to get the Forged Seal of Ascension item.
3. Return to Vaelan in LBRS to complete the quest.

**Comment by SoloCraftServer** [comment]
Hello, I can't reproduce the issue, it works fine to me. Can you please close wow and remove the Cache/WDB folder and try again please?

**Comment by OleIdole** [comment]
^after you turn in the first quest that leads to dustwallow marsh, it takes your "Unadorned Seal of Ascension" (that makes Vaelan) change into a questgiver state. So you just need to kill a few mobs next to Vaelan and loot a new one, then he will work as questgiver again.
