### ISSUE TITLE
Buffing order

### ISSUE THREAD

**Issue by OleIdole** [SoloCraftServer/bugtracker#66]
## 🐛 Bug report
Very similar issue to resurrection order #56. All bots buff the same targets so instead of e.g. 5 priests giving stamina buff to 5 different groups, they all cast it on the same group at the same time. This makes buffing extremely slow compared to what it should be. This gets even worse on single target buffs like thorns.

### Expected behavior
Have bots buff in different order of players so they buff multiple people at the same time instead of same target.

### Steps to reproduce
1. Make raid and fill with 39 priests
2. Notice how all priests will buff group 8, then all priests will buff group 7 and so on, with a partywide buff.

**Comment by SoloCraftServer** [comment]
The priests didn't buff eachother at all, spawned 39 priests and buffing was complete in few seconds. The current buffing system is fine and will remain like it is. Also the bots only buff while out of combat.

**Comment by OleIdole** [comment]
my bad on the steps, priests always selfbuff first. So the correct reproduce steps would be to spawn 5 priests in 1 grp and warriors in other grps then see that all 5 priests buff same grp.
