### ISSUE TITLE
Bots not using weapon oil/stones given to them

### ISSUE THREAD

**Issue by OleIdole** [SoloCraftServer/bugtracker#67]
## 🐛 Bug report
We already see bots using consumables that we trade them. But this does not happen for consumables that are applied to weapons such as oils or sharpening/weightstones.

### Expected behavior
When trading a bot a weapon oil/stone consumable, they should apply it to their weapon if possible (preferably mainhand first).

### Steps to reproduce
1. Spawn bot warrior meleedps
2. Trade him Dense Sharpening Stone
3. Watch his behaviour and inspect him (nothing happens, the stone is not applied to his sword).

**Comment by SoloCraftServer** [comment]
The partybots only do equip gear and consume scrolls/flasks/potions only.
