### ISSUE TITLE
partybot clone missing enchants

### ISSUE THREAD

**Issue by OleIdole** [SoloCraftServer/bugtracker#68]
## 🐛 Bug report
Enchants does not get copied to the bot with .partybot clone

### Expected behavior
All the enchants from the player should also be applied to the gear on the clone

### Steps to reproduce
1. enchant some of your gear
2. do .partybot clone
3. inspect bot to see no enchant

**Comment by SoloCraftServer** [comment]
The command clone will only clone the character items and will remain like that.
