### ISSUE TITLE
Crossfaction not working pvp

### ISSUE THREAD

**Issue by OleIdole** [SoloCraftServer/bugtracker#69]
## 🐛 Bug report
Ticketed ingame and was told to post this here:
While server is crossfaction, it is not possible to queue to battlegrounds with opposite faction.
Me and my brother made opposite faction characters since crossfaction made faction not matter. But when you queue to battleground together it says cannot queue with opposite faction.

### Expected behavior
Queue battleground together regardless of faction in the group.

### Steps to reproduce
1. Be horde
2. Invite alliance player
3. Try to queue group to battleground

**Comment by SoloCraftServer** [comment]
We do not have crossfaction battlegrounds, the BG system is blizzlike so you cannot group up with a player from the opposite faction.

**Comment by SoloCraftServer** [comment]
If we ever decide to implement crossfaction battlegrounds, we'll announce it on the forums
