### ISSUE TITLE
"Skinning" Creature needs to be looted first

### ISSUE THREAD

**Issue by herounit210** [SoloCraftServer/bugtracker#74]
## 🐛 Bug report
 when you try to skin creature that doesn't drop any items it seems the game confusedcinto thinking it needs to drop an item first before it can be skinned. You can only skin creatures that do drop items and it's frustrating.

### Expected behavior

You should be able to skin creatures that don't drop any loot. 
### Steps to reproduce
1. Slay any creature,(boar scorpion, etc) 
2. After being slayed if it does not drop an item you will get a "creatures needs to be looted first" error and you cannot skin the creature
3. If creature does drop an item, loot it, and you can skin it. Although if it drops an item that can be rolled on it will be glitches and constantly appear to be unlooted. (Sparkling and showing bag icon)

**Comment by SoloCraftServer** [comment]
Make sure you set loot to FFA if you are in a party (or with bots)
