### ISSUE TITLE
Healers

### ISSUE THREAD

**Issue by Bishooi** [SoloCraftServer/bugtracker#8]
## 🐛 Bug report

Healers as a whole need work. We had 10+ heals in one raid and they could not heal the raid. Heals also cannt heal 5 man people will die and generally wipe 9/10
### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
I'll mark this as invalid since this is not a clear report. Players cleared dungeons perfectly fine. Provide info if you want to report a class, spec or setup
