### ISSUE TITLE
Uncovering the Past

### ISSUE THREAD

**Issue by brotemant** [SoloCraftServer/bugtracker#80]
## 🐛 Bug report
2 of 4 fragments required by the quest "Uncovering the Past" are missing in the Wetlands Whelgar's excavation site.

### Expected behavior
3 different ancient relics and 1 loose soil to exist in the Wetlands Whelgar's excavation site.

### Steps to reproduce
1. Search for ancient relic
2. Not find 1 of 3 ancient relics
3. Search for loose soil
4. Nof find the loose soil

**Comment by SoloCraftServer** [comment]
![image](https://user-images.githubusercontent.com/116836123/221360503-f00ebc8d-5fcf-478b-b485-73b707ada447.png)
