### ISSUE TITLE
Lord Kri has a spell he shouldnt have

### ISSUE THREAD

**Issue by Opek404** [SoloCraftServer/bugtracker#84]
## 🐛 Bug report

Lord Kri in the AQ40 bug trio has poison volley when only vem should have it
### Expected behavior

Only vem should have poison volley, Its shows in your combat log when Lord Kri hits you with poison volley
### Steps to reproduce
1.Do 2 bug fight in aq40
2.
3.

**Comment by SoloCraftServer** [comment]
![image](https://user-images.githubusercontent.com/116836123/222722374-c70976c7-c1e1-4d6a-bf97-06f39de06612.png)

Lord Kri doesn't have any poison volley spell, only Toxic Volley which is blizzlike.
https://www.wowhead.com/classic/spell=21687/toxic-volley

**Comment by Opek404** [comment]
https://www.wowhead.com/classic/npc=15511/lord-kri#abilities;mode:40player
Lord kri shouldn’t have any volley only Vem.
