### ISSUE TITLE
Hunter Pet unable to revive, also unable to train a new one

### ISSUE THREAD

**Issue by B1ackWaltz** [SoloCraftServer/bugtracker#85]
## 🐛 Bug report

As a hunter my pet died. I tried reviving and the game said I don't have a pet to revive.
Tried taming a new pet, got through the taming animation, only to be told I can't tame a new pet as I've already got one.
### Expected behavior

Pet should either be revivable or not attached to me so I can tame a new one.

Proof:
That's how the game works?

### Steps to reproduce
1.revive pet. fails
2.tame new pet. fails
3.
![revive](https://user-images.githubusercontent.com/126959235/222900077-b43defb6-529f-4382-bf80-58c1445e9339.png)
![tame](https://user-images.githubusercontent.com/126959235/222900082-bb69b595-9ce2-4f10-bc47-d44d37bfc6be.png)

**Comment by SoloCraftServer** [comment]
You need to call your pet first then use revive, I can't reproduce it like you explained
