### ISSUE TITLE
Eye of Hakkar only sells for 1 copper

### ISSUE THREAD

**Issue by Opek404** [SoloCraftServer/bugtracker#88]
## 🐛 Bug report

The neck [The Eye of Hakkar] only sells for 1 copper when it should be like 4g 60s
### Expected behavior
]
![eyeofhak](https://user-images.githubusercontent.com/125311874/223153714-0ba89601-17d5-480e-85d9-a42d6214a67d.PNG)
![image](https://user-images.githubusercontent.com/125311874/223153895-1a81df3d-2b62-4895-9fcd-d356ec9e224a.png)

### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
It sells for 4g86s28c. Clear your cache files.
