### ISSUE TITLE
Guild Charter

### ISSUE THREAD

**Issue by Veldane** [SoloCraftServer/bugtracker#9]
## 🐛 Bug report

Guild charter isn't allowing people to sign
### Expected behavior

player should have option to accept or deny
### Steps to reproduce
1.create a guild charter
2.target a player
3.hit button for them to read the charter

**Comment by SoloCraftServer** [comment]
Hello Valdane, I've tested it several times and it works as intended, you always may open a ticket ingame so we can create the guild for you.
