### ISSUE TITLE
Cannot choose talents (Horde Troll Priest)

### ISSUE THREAD

**Issue by Borris37** [SoloCraftServer/bugtracker#94]
## 🐛 Bug report

At any given level, I cannot spend my talent points as I wish. I can only choose certain talents among the available talents.  i.e. In the first tier/row I could only spend points in the first 2 talents but not third. It's as if the game is forcing me to choose a specific class build. This is the case on all tiers. I have only been playing a Horde Troll Priest and have not heard anyone else say they have talent issues.
### Expected behavior

I should be able to spend points freely on available talents. This is how the game is supposed to function.
### Steps to reproduce
1. I have talents to spend
2. I try to spend them on talents I want that are available to my level
3. I cannot choose talents I want out of what is actually available

**Comment by SoloCraftServer** [comment]
Try clear your WDB folder (Cache) if it doesn't work, dm me on Discord of forum and let me know your character name
