### ISSUE TITLE
Invisible Wall in the Scarlet Monestary entry stairwell

### ISSUE THREAD

**Issue by Borris37** [SoloCraftServer/bugtracker#95]
## 🐛 Bug report

There is an invisible wall in the stairwell in front of Scarlet Monestary, the stairs that lead to the room with all of the instances. This prevents entry to all SM instances.
### Expected behavior

There should be no invisible wall. I should be able to walk up the stairs.
### Steps to reproduce
1. Enter the entryway of SM
2. Walk up the stairs leading to instances room
3. There is an invisible wall about 3/4 of the way up, preventing access to the instances

I was gonna post a screenshot of the exact spot, but this forum does not support the screenshot file format (TGA)

**Comment by SoloCraftServer** [comment]
I can't reproduce it, please upload a screenshot (TGA can be converted into jpg online) or dm on Discord.

**Comment by SoloCraftServer** [comment]
Also make sure you are using a clean 1.12 client and not modified one.
