### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by David000014** [SoloCraftServer/bugtracker#96]
![LinderBug](https://user-images.githubusercontent.com/129520479/229130585-6d71d29f-f463-49d9-8229-ce32b1c8429a.jpg)
## 🐛 Bug report

Basically, if you can't loot an animal the skinning action is blocked/canceled -those you can loot first you can skin after but thats maybe 1 out of every 4 to 6 animals killed that just lays there
### Steps to reproduce
1.
2.
3.

**Comment by SoloCraftServer** [comment]
You have to set your loot settings to free for all. Otherwise your bot "must" loot it before you can skin it.

**Comment by David000014** [comment]
Thank you
