### ISSUE TITLE
Anubisath Defenders AQ40 Disconnect bug

### ISSUE THREAD

**Issue by Evisceratechuck** [SoloCraftServer/bugtracker#97]
## 🐛 Bug report

Whenever I approach the trash mobs outside Twins, Anubisath Defender, my game freezes, I teleport to the last defender thus aggro ALL other defenders and then I usually get a disconnect.

### Expected behavior

Like it did before they all aggroed, teleported me around and disconnected me from the game.

### Steps to reproduce
1. Aggro defender.
2. Get teleported
3. Die and/or get disconnected

**Comment by SoloCraftServer** [comment]
Will be fixed after next restart
