### ISSUE TITLE
Healer bots performing poorly in lvl 48 range 

### ISSUE THREAD

**Issue by Raigdar** [SoloCraftServer/bugtracker#99]
## 🐛 Bug report
Bots in the lvl 48 range especially healers are really poorly performing (more than usual). We are dying in dungeons at almost every pack because of the healer not using high enough heal ranks.

For example, spawned druid healers buff with Mark of the Wild Rank 2 and sometimes rank 3 and use only rejuvenation and healing touch (low ranks), never have i seen one druid healer use Regrowth.
Priests buff with Fortitude rank 2 and some times rank 3 and use low ranks of renew and heals (never big heals to top of with low health)
Havent played with paladin healers much, but when i spawn them they ALWAYS use blessing of wisdom, even on melee classes.

### Expected behavior
Just want healers to buff with max rank and heal with higher ranks to keep a tank alive. (downranking is ofcourse useful, but not all the time when you need to heal big)

### Steps to reproduce
1. Be in the range of level 48
2. Go into Maraudon purple side
3. Try and survive just one pack at the time.

**Comment by Saniok88** [comment]
it even happens even until level 59 (including), they heal for 450-500 hp (just like if they were using a very low rank of heal from level 25-35), it happens at least with priests and druids (maybe even all healer classes without exceptions)

**Comment by SoloCraftServer** [comment]
Lower level bots are coded to use lower ranks if possible to save mana. Level 60 bots are more optimized for running dungeons/raids. Also, don't forget to convert your group into a raid so you will be able to spawn more bots (or healers).
